---
permalink: sg6000/accessing-and-configuring-santricity-system-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, SANtricity System Manager, SANtricity, System Manager, configure, configuring, setup, set up, setting up, access, accessing, E-Series AutoSupport, autosupport 
summary: 'È possibile utilizzare Gestore di sistema di SANtricity per monitorare lo stato dei controller di storage, dei dischi di storage e di altri componenti hardware nello shelf del controller di storage. È inoltre possibile configurare un proxy per e-Series AutoSupport che consente di inviare messaggi AutoSupport dall"appliance senza utilizzare la porta di gestione.' 
---
= Accesso e configurazione di Gestore di sistema di SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema di SANtricity per monitorare lo stato dei controller di storage, dei dischi di storage e di altri componenti hardware nello shelf del controller di storage. È inoltre possibile configurare un proxy per e-Series AutoSupport che consente di inviare messaggi AutoSupport dall'appliance senza utilizzare la porta di gestione.

.Fasi
* link:setting-up-and-accessing-santricity-system-manager.html["Configurazione e accesso a Gestore di sistema di SANtricity"]
* link:reviewing-hardware-status-in-santricity-system-manager.html["Analisi dello stato dell'hardware in Gestore di sistema di SANtricity"]
* link:setting-ip-addresses-for-storage-controllers-using-storagegrid-appliance-installer.html["Impostazione degli indirizzi IP dei controller di storage mediante il programma di installazione dell'appliance StorageGRID"]

