---
permalink: sg6000/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Prima di poter implementare un"appliance StorageGRID come nodo di storage in un sistema StorageGRID, è necessario configurare le connessioni tra l"appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell"appliance StorageGRID, preinstallato sul controller SG6000-CN (controller di calcolo).' 
---
= Configurazione delle connessioni StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter implementare un'appliance StorageGRID come nodo di storage in un sistema StorageGRID, è necessario configurare le connessioni tra l'appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell'appliance StorageGRID, preinstallato sul controller SG6000-CN (il controller di calcolo).

.Fasi
* link:accessing-storagegrid-appliance-installer-sg6000.html["Accesso al programma di installazione dell'appliance StorageGRID"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verifica e aggiornamento della versione del programma di installazione dell'appliance StorageGRID"]
* link:configuring-network-links-sg6000.html["Configurazione dei collegamenti di rete (SG6000)"]
* link:configuring-storagegrid-ip-addresses-sg6000.html["Configurazione degli indirizzi IP StorageGRID"]
* link:verifying-network-connections.html["Verifica delle connessioni di rete"]
* link:verifying-port-level-network-connections.html["Verifica delle connessioni di rete a livello di porta"]

