---
permalink: sg6000/configuring-bmc-interface-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interfaccia utente del controller di gestione della scheda base (BMC) sul controller SG6000-CN fornisce informazioni sullo stato dell"hardware e consente di configurare le impostazioni SNMP e altre opzioni per il controller SG6000-CN.' 
---
= Configurazione dell'interfaccia BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente del BMC (Baseboard Management Controller) sul controller SG6000-CN fornisce informazioni sullo stato dell'hardware e consente di configurare le impostazioni SNMP e altre opzioni per il controller SG6000-CN.

.Fasi
* link:changing-root-password-for-bmc-interface-sg6000.html["Modifica della password root per l'interfaccia BMC"]
* link:setting-ip-address-for-bmc-management-port-sg6000.html["Impostazione dell'indirizzo IP per la porta di gestione BMC"]
* link:accessing-bmc-interface-sg6000.html["Accesso all'interfaccia BMC"]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html["Configurazione delle impostazioni SNMP per il controller SG6000-CN"]
* link:setting-up-email-notifications-for-alerts.html["Impostazione delle notifiche e-mail per gli avvisi"]

