---
permalink: audit/event-specific-data.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, event, data 
summary: Ogni messaggio di audit nel registro di audit registra i dati specifici di un evento di sistema. 
---
= Dati specifici dell'evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni messaggio di audit nel registro di audit registra i dati specifici di un evento di sistema.

Dopo l'apertura `[AUDT:` container che identifica il messaggio stesso, il successivo set di attributi fornisce informazioni sull'evento o sull'azione descritti dal messaggio di audit. Questi attributi sono evidenziati nel seguente esempio:

`2018-12-05T08:24:45.921845 *[AUDT:[RSLT(FC32):SUCS]*` +
`*[TIME(UI64):11454] [SAIP(IPAD):"10.224.0.100"] [S3AI(CSTR):"60025621595611246499"]*`
`[*SACC(CSTR):"account"] [S3AK(CSTR):"SGKH4_Nc8SO1H6w3w0nCOFCGgk__E6dYzKlumRsKJA=="]*`
`*[SUSR(CSTR):"urn:sgws:identity::60025621595611246499:root"]*` +
`*[SBAI(CSTR):"60025621595611246499"] [SBAC(CSTR):"account"] [S3BK(CSTR):"bucket"]*` +
`*[S3KY(CSTR):"object"] [CBID(UI64):0xCC128B9B9E428347]*` +
`*[UUID(CSTR):"B975D2CE-E4DA-4D14-8A23-1CB4B83F2CD8"] [CSIZ(UI64):30720]* [AVER(UI32):10]`
`[ATIM(UI64):1543998285921845] [ATYP(FC32):SHEA] [ANID(UI32):12281045] [AMID(FC32):S3RQ]`
`[ATID(UI64):15552417629170647261]]`

Il `ATYP` element (sottolineato nell'esempio) identifica l'evento che ha generato il messaggio. Questo messaggio di esempio include il codice del messaggio SHEA ([ATYP(FC32):SHEA]), che indica che è stato generato da una richiesta S3 HEAD riuscita.

.Informazioni correlate
link:common-elements-in-audit-messages.html["Elementi comuni nei messaggi di audit"]

link:audit-messages-main.html["Messaggi di audit"]
