---
settings:
  name: StorageGRID 11.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - name: StorageGRID
    url: "/storagegrid-115"
    version-number: '11.5'
  - name: StorageGRID
    url: "/storagegrid-116"
    version-number: '11.6'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63374&language=en-US
    version-number: '11.4'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023&archive=true
    version-number: '11.3'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.5 documenti
    url: "/index.html"
  - section: release-notes
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
  - title: Installare e aggiornare il software
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Installazione e manutenzione dell'hardware
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Configurare e gestire
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e risolvere i problemi
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantenere
    entries:
    - section: expand
    - section: maintain
  - title: Altre versioni
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: "/release-notes/index.html"
    - title: Novità
      url: "/upgrade/whats-new.html"
    - title: Scopri di più su StorageGRID
      url: "/primer/index.html"
    - title: Linee guida per il networking
      url: "/network/index.html"
  - title: Installare l'hardware di manutenzione
    links:
    - title: Appliance di storage SG6000
      url: "/sg6000/index.html"
    - title: Appliance di storage SG5700
      url: "/sg5700/index.html"
    - title: Appliance di storage SG5600
      url: "/sg5600/index.html"
    - title: Appliance di servizi SG100 e SG1000
      url: "/sg100-1000/index.html"
  - title: Installare il software di aggiornamento
    links:
    - title: Installare Red Hat Enterprise Linux o CentOS
      url: "/rhel/index.html"
    - title: Installare Ubuntu o Debian
      url: "/ubuntu/index.html"
    - title: Installare VMware
      url: "/vmware/index.html"
    - title: Aggiornare il software
      url: "/upgrade/index.html"
  - title: Configurare la griglia
    links:
    - title: Amministrare StorageGRID
      url: "/admin/index.html"
    - title: Gestire gli oggetti con ILM
      url: "/ilm/index.html"
    - title: Protezione avanzata del sistema
      url: "/harden/index.html"
    - title: Configurare StorageGRID per FabricPool
      url: "/fabricpool/index.html"
  - title: Gestire gli oggetti
    links:
    - title: Utilizzare un account tenant
      url: "/tenant/index.html"
    - title: UTILIZZARE L'API REST S3
      url: "/s3/index.html"
    - title: Utilizzare l'API REST di Swift
      url: "/swift/index.html"
  - title: Monitorare e gestire
    links:
    - title: Monitorare
      url: "/monitor/index.html"
    - title: Risolvere i problemi
      url: "/troubleshoot/troubleshooting-storagegrid-system.html"
    - title: Esaminare i registri di audit
      url: "/audit/index.html"
    - title: Espandi il tuo grid
      url: "/expand/index.html"
    - title: Ripristino e manutenzione
      url: "/maintain/index.html"
  - title: Tutorial sulle demo
    links:
    - title: Scopri come attivare StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: Videoteca StorageGRID
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: Servizi di apprendimento NetApp
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Più risorse
    links:
    - title: Pagina di supporto di StorageGRID
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: Tool di matrice di interoperabilità NetApp (IMT)
      url: https://imt.netapp.com/matrix/#welcome
    - title: Knowledge base di StorageGRID
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: Blog di NetApp
      url: https://netapp.com/blog/
    - title: Community di NetApp
      url: https://community.netapp.com/
  - title: Altre versioni
    links:
    - title: Documentazione di StorageGRID 11.7
      url: https://docs.netapp.com/us-en/storagegrid-117/index.html
    - title: Documentazione di StorageGRID 11.6
      url: https://docs.netapp.com/us-en/storagegrid-116/index.html
    - title: Documentazione di StorageGRID 11.4
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: Documentazione di StorageGRID 11.3
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: Documentazione di StorageGRID 11.2
      url: https://docs.netapp.com/sgws-112/index.jsp
