---
settings:
  name: StorageGRID 11.5
  search: storagegrid-enable,storagegrid-115
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.5 documenti
    url: "/index.html"
  - section: release-notes
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
  - title: Installare e aggiornare il software
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Installazione e manutenzione dell'hardware
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Configurare e gestire
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e risolvere i problemi
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantenere
    entries:
    - section: expand
    - section: maintain
  - title: Altre versioni
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
