---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11.5 utilizza la versione 3 dell"API di gestione dei tenant. La versione 3 è obsoleta della versione 2; tuttavia, la versione 1 e la versione 2 sono ancora supportate.' 
---
= Modifiche all'API di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5 utilizza la versione 3 dell'API di gestione dei tenant. La versione 3 è obsoleta della versione 2; tuttavia, la versione 1 e la versione 2 sono ancora supportate.


IMPORTANT: È possibile continuare a utilizzare la versione 1 e la versione 2 dell'API di gestione con StorageGRID 11.5; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una release futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 11.5, le API v1 e v2 obsolete possono essere disattivate utilizzando `PUT /grid/config/management` API.



== Nuovo parametro per l'API di utilizzo dello storage del tenant

Il `GET /org/usage` L'API ora dispone di un `strictConsistency` parametro. Per applicare una coerenza forte e globale durante il recupero delle informazioni sull'utilizzo dello storage nei nodi di storage, impostare questo parametro su `true`. Quando questo parametro è impostato su `false` (Impostazione predefinita), StorageGRID tenta di recuperare le informazioni di utilizzo utilizzando una coerenza globale forte, ma ritorna alla coerenza del sito forte se non è possibile soddisfare una coerenza globale forte.

.Informazioni correlate
link:../s3/index.html["Utilizzare S3"]

link:../tenant/index.html["Utilizzare un account tenant"]
