---
permalink: sg100-1000/configuring-storagegrid-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, storagegrid connections, connections, configure, setup, set up 
summary: 'Prima di poter implementare l"appliance di servizi come nodo in un sistema StorageGRID, è necessario configurare le connessioni tra l"appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell"appliance StorageGRID, preinstallato sull"appliance di servizi.' 
---
= Configurazione delle connessioni StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter implementare l'appliance di servizi come nodo in un sistema StorageGRID, è necessario configurare le connessioni tra l'appliance e le reti che si intende utilizzare. È possibile configurare la rete consultando il programma di installazione dell'appliance StorageGRID, preinstallato sull'appliance di servizi.

.Fasi
* link:accessing-storagegrid-appliance-installer-sg100-and-sg1000.html["Accesso al programma di installazione dell'appliance StorageGRID"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verifica e aggiornamento della versione del programma di installazione dell'appliance StorageGRID"]
* link:configuring-network-links-sg100-and-sg1000.html["Configurazione dei collegamenti di rete (SG100 e SG1000)"]
* link:configuring-storagegrid-ip-addresses-sg100-and-sg1000.html["Configurazione degli indirizzi IP StorageGRID"]
* link:verifying-network-connections.html["Verifica delle connessioni di rete"]
* link:verifying-port-level-network-connections.html["Verifica delle connessioni di rete a livello di porta"]

