---
permalink: sg100-1000/preparing-for-installation-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, install, installation, preparation, get ready, prepare 
summary: 'La preparazione dell"installazione di un"appliance StorageGRID richiede la preparazione del sito e l"ottenimento di tutti gli hardware, i cavi e gli strumenti necessari. È inoltre necessario raccogliere gli indirizzi IP e le informazioni di rete.' 
---
= Preparazione per l'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La preparazione dell'installazione di un'appliance StorageGRID richiede la preparazione del sito e l'ottenimento di tutti gli hardware, i cavi e gli strumenti necessari. È inoltre necessario raccogliere gli indirizzi IP e le informazioni di rete.

.Fasi
* link:preparing-site-sg100-and-sg1000.html["Preparazione del sito (SG100 e SG1000)"]
* link:unpacking-boxes-sg100-and-sg1000.html["Disimballaggio delle confezioni (SG100 e SG1000)"]
* link:obtaining-additional-equipment-and-tools-sg100-and-sg1000.html["Come ottenere apparecchiature e strumenti aggiuntivi (SG100 e SG1000)"]
* link:web-browser-requirements.html["Requisiti del browser Web"]
* link:reviewing-appliance-network-connections-sg100-and-sg1000.html["Analisi delle connessioni di rete dell'appliance"]
* link:gathering-installation-information-sg100-and-sg1000.html["Raccolta delle informazioni di installazione (SG100 e SG1000)"]

