---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: 'Prima di installare l"appliance StorageGRID, è necessario conoscere le reti che è possibile collegare all"appliance.' 
---
= Analisi delle connessioni di rete dell'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare l'appliance StorageGRID, è necessario conoscere le reti che è possibile collegare all'appliance.

Quando si implementa un'appliance StorageGRID come nodo in un sistema StorageGRID, è possibile collegarla alle seguenti reti:

* *Grid Network per StorageGRID*: La Grid Network viene utilizzata per tutto il traffico StorageGRID interno. Fornisce connettività tra tutti i nodi della rete, in tutti i siti e le subnet. La rete grid è obbligatoria.
* *Rete amministrativa per StorageGRID*: La rete amministrativa è una rete chiusa utilizzata per l'amministrazione e la manutenzione del sistema. La rete di amministrazione è in genere una rete privata e non deve essere instradabile tra i siti. La rete di amministrazione è opzionale.
* *Rete client per StorageGRID:* la rete client è una rete aperta utilizzata per fornire l'accesso alle applicazioni client, tra cui S3 e Swift. La rete client fornisce l'accesso del protocollo client alla griglia, in modo che la rete griglia possa essere isolata e protetta. È possibile configurare la rete client in modo che sia possibile accedere all'appliance tramite questa rete utilizzando solo le porte che si sceglie di aprire. La rete client è opzionale.
* *BMC management network for the Services appliance:* questa rete fornisce l'accesso al controller di gestione della baseboard in SG100 e SG1000, appliance che consentono di monitorare e gestire i componenti hardware dell'appliance. Questa rete di gestione può essere la stessa della rete di amministrazione per StorageGRID o può essere una rete di gestione indipendente.


.Informazioni correlate
link:gathering-installation-information-sg100-and-sg1000.html["Raccolta delle informazioni di installazione (SG100 e SG1000)"]

link:cabling-appliance-sg100-and-sg1000.html["Cablaggio dell'appliance SG100 e SG1000)"]

link:../network/index.html["Linee guida per la rete"]

link:../primer/index.html["Primer griglia"]
