---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords:  
summary: È necessario installare Ubuntu o Debian su tutti gli host grid. Utilizza NetApp Interoperability Matrix Tool per ottenere un elenco delle versioni supportate. 
---
= Installazione di Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare Ubuntu o Debian su tutti gli host grid. Utilizza NetApp Interoperability Matrix Tool per ottenere un elenco delle versioni supportate.

.Fasi
. Installare Ubuntu o Debian su tutti gli host di griglia fisici o virtuali secondo le istruzioni del distributore o la procedura standard.
+

NOTE: Non installare ambienti desktop grafici. Quando si installa Ubuntu, è necessario selezionare *utility di sistema standard*. Si consiglia di selezionare *OpenSSH server* per abilitare l'accesso ssh agli host Ubuntu. Tutte le altre opzioni possono rimanere deselezionate.

. Assicurarsi che tutti gli host abbiano accesso ai repository dei pacchetti di Ubuntu o Debian.
. Se lo swap è attivato:
+
.. Eseguire il seguente comando: `$ sudo swapoff --all`
.. Rimuovere tutte le voci di swap da `/etc/fstab` per mantenere le impostazioni.


+

IMPORTANT: La mancata disattivazione completa dello swap può ridurre notevolmente le performance.



.Informazioni correlate
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
