---
permalink: ubuntu/installation-overview.html 
sidebar: sidebar 
keywords:  
summary: 'L"installazione di un sistema StorageGRID in un ambiente Ubuntu o Debian include tre passaggi principali.' 
---
= Panoramica dell'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installazione di un sistema StorageGRID in un ambiente Ubuntu o Debian include tre passaggi principali.

. *Preparazione*: Durante la pianificazione e la preparazione, si eseguono le seguenti attività:
+
** Scopri i requisiti hardware e storage per StorageGRID.
** Scopri le specifiche del networking StorageGRID per configurare la rete in modo appropriato. Per ulteriori informazioni, consultare le linee guida per il collegamento in rete di StorageGRID.
** Identificare e preparare i server fisici o virtuali che si intende utilizzare per ospitare i nodi grid StorageGRID.
** Sui server preparati:
+
*** Installare Ubuntu o Debian
*** Configurare la rete host
*** Configurare lo storage host
*** Installare Docker
*** Installare i servizi host di StorageGRID




. *Implementazione*: Implementare i nodi grid utilizzando l'interfaccia utente appropriata. Quando si implementano nodi grid, questi vengono creati come parte del sistema StorageGRID e connessi a una o più reti.
+
.. Usare la riga di comando e i file di configurazione del nodo di Ubuntu o Debian per distribuire nodi virtual grid sugli host preparati al punto 1.
.. Utilizzare il programma di installazione dell'appliance StorageGRID per implementare i nodi dell'appliance StorageGRID.
+

NOTE: Le istruzioni di installazione e integrazione specifiche dell'hardware non sono incluse nella procedura di installazione di StorageGRID. Per informazioni su come installare le appliance StorageGRID, consultare le istruzioni di installazione e manutenzione dell'appliance.



. *Configurazione*: Una volta implementati tutti i nodi, utilizzare Grid Manager per configurare la griglia e completare l'installazione.


Queste istruzioni consigliano un approccio standard per la distribuzione e la configurazione di un sistema StorageGRID in un ambiente Ubuntu o Debian. Vedere anche le informazioni sui seguenti approcci alternativi:

* Utilizzare un framework di orchestrazione standard come Ansible, Puppet o Chef per installare Ubuntu o Debian, configurare il networking e lo storage, installare Docker e il servizio host StorageGRID e distribuire nodi virtual grid.
* Automatizzare la distribuzione e la configurazione del sistema StorageGRID utilizzando uno script di configurazione Python (fornito nell'archivio di installazione).
* Automatizza l'implementazione e la configurazione dei nodi grid dell'appliance con uno script di configurazione Python (disponibile dall'archivio di installazione o dal programma di installazione dell'appliance StorageGRID).
* Se sei uno sviluppatore avanzato di implementazioni StorageGRID, utilizza le API REST di installazione per automatizzare l'installazione dei nodi grid StorageGRID.


.Informazioni correlate
link:planning-and-preparation.html["Pianificazione e preparazione"]

link:deploying-virtual-grid-nodes.html["Implementazione di nodi virtual grid"]

link:configuring-grid-and-completing-installation.html["Configurazione della griglia e completamento dell'installazione"]

link:automating-installation-and-configuration-of-storagegrid-host-service.html["Automazione dell'installazione e della configurazione del servizio host StorageGRID"]

link:overview-of-installation-rest-api.html["Panoramica dell'API REST per l'installazione"]

link:../network/index.html["Linee guida per la rete"]
