---
permalink: ubuntu/required-materials.html 
sidebar: sidebar 
keywords:  
summary: Prima di installare StorageGRID, è necessario raccogliere e preparare il materiale necessario. 
---
= Materiali richiesti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare StorageGRID, è necessario raccogliere e preparare il materiale necessario.

|===
| Elemento | Note 


 a| 
Licenza NetApp StorageGRID
 a| 
È necessario disporre di una licenza NetApp valida con firma digitale.

*Nota*: Una licenza non di produzione, che può essere utilizzata per il test e le griglie di prova, è inclusa nell'archivio di installazione di StorageGRID.



 a| 
Archivio di installazione di StorageGRID
 a| 
È necessario scaricare l'archivio di installazione di StorageGRID ed estrarre i file.



 a| 
Laptop di assistenza
 a| 
Il sistema StorageGRID viene installato tramite un laptop di assistenza.

Il laptop di assistenza deve disporre di:

* Porta di rete
* Client SSH (ad esempio, putty)
* Browser Web supportato




 a| 
Documentazione StorageGRID
 a| 
* Note di rilascio
* Istruzioni per l'amministrazione di StorageGRID


|===
.Informazioni correlate
link:downloading-and-extracting-storagegrid-installation-files.html["Download ed estrazione dei file di installazione di StorageGRID"]

link:web-browser-requirements.html["Requisiti del browser Web"]

link:../admin/index.html["Amministrare StorageGRID"]

link:../release-notes/index.html["Note di rilascio"]
