---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: Se si prevede di utilizzare i servizi della piattaforma StorageGRID o i pool di storage cloud, è necessario configurare il grid networking e i firewall per garantire che gli endpoint di destinazione possano essere raggiunti. I servizi della piattaforma includono servizi esterni che forniscono integrazione della ricerca, notifica degli eventi e replica di CloudMirror. 
---
= Networking e porte per servizi di piattaforma e Cloud Storage Pool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si prevede di utilizzare i servizi della piattaforma StorageGRID o i pool di storage cloud, è necessario configurare il grid networking e i firewall per garantire che gli endpoint di destinazione possano essere raggiunti. I servizi della piattaforma includono servizi esterni che forniscono integrazione della ricerca, notifica degli eventi e replica di CloudMirror.

I servizi della piattaforma richiedono l'accesso dai nodi di storage che ospitano il servizio ADC StorageGRID agli endpoint del servizio esterno. Esempi per fornire l'accesso includono:

* Sui nodi di storage con servizi ADC, configurare reti amministrative univoche con voci AESL che instradano verso gli endpoint di destinazione.
* Fare affidamento sul percorso predefinito fornito da una rete client. In questo esempio, è possibile utilizzare la funzione Untrusted Client Network per limitare le connessioni in entrata.


I pool di cloud storage richiedono inoltre l'accesso dai nodi di storage agli endpoint forniti dal servizio esterno utilizzato, come Amazon S3 Glacier o Microsoft Azure Blob.

Per impostazione predefinita, i servizi della piattaforma e le comunicazioni del Cloud Storage Pool utilizzano le seguenti porte:

* *80*: Per gli URI endpoint che iniziano con `http`
* *443*: Per gli URI endpoint che iniziano con `https`


È possibile specificare una porta diversa quando si crea o si modifica l'endpoint.

Se si utilizza un server proxy non trasparente, è necessario configurare anche le impostazioni del proxy per consentire l'invio dei messaggi a endpoint esterni, ad esempio un endpoint su Internet. Per informazioni su come configurare le impostazioni del proxy, consultare la sezione Administering StorageGRID (Amministrazione di Windows)

Per ulteriori informazioni sulle reti client non attendibili, consultare le istruzioni per l'amministrazione di StorageGRID. Per ulteriori informazioni sui servizi della piattaforma, consultare le istruzioni per l'utilizzo degli account tenant. Per ulteriori informazioni sui Cloud Storage Pools, consulta le istruzioni per la gestione degli oggetti con la gestione del ciclo di vita delle informazioni.

.Informazioni correlate
link:network-port-reference.html["Riferimento porta di rete"]

link:../primer/index.html["Primer griglia"]

link:../admin/index.html["Amministrare StorageGRID"]

link:../tenant/index.html["Utilizzare un account tenant"]

link:../ilm/index.html["Gestire gli oggetti con ILM"]
