---
permalink: network/post-installation-guidelines.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver completato l"implementazione e la configurazione del nodo griglia, seguire queste linee guida per l"indirizzamento DHCP e le modifiche alla configurazione di rete.' 
---
= Linee guida per la post-installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato l'implementazione e la configurazione del nodo griglia, seguire queste linee guida per l'indirizzamento DHCP e le modifiche alla configurazione di rete.

* Se si utilizza DHCP per assegnare indirizzi IP, configurare una prenotazione DHCP per ciascun indirizzo IP sulle reti utilizzate.
+
È possibile configurare DHCP solo durante la fase di implementazione. Non è possibile impostare DHCP durante la configurazione.

+

IMPORTANT: I nodi si riavviano quando cambiano gli indirizzi IP, causando interruzioni se una modifica dell'indirizzo DHCP influisce su più nodi contemporaneamente.

* Per modificare gli indirizzi IP, le subnet mask e i gateway predefiniti di un nodo griglia, è necessario utilizzare le procedure Change IP (Modifica IP). Consultare le informazioni sulla configurazione degli indirizzi IP nelle istruzioni di ripristino e manutenzione.
* Se si apportano modifiche alla configurazione di rete, incluse modifiche al routing e al gateway, la connettività del client al nodo di amministrazione primario e ad altri nodi della griglia potrebbe andare persa. A seconda delle modifiche di rete applicate, potrebbe essere necessario ristabilire queste connessioni.


.Informazioni correlate
link:../rhel/index.html["Installare Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Installare Ubuntu o Debian"]

link:../vmware/index.html["Installare VMware"]

link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]

link:../sg6000/index.html["Appliance di storage SG6000"]

link:../sg5700/index.html["Appliance di storage SG5700"]

link:../sg5600/index.html["Appliance di storage SG5600"]

link:../maintain/index.html["Mantieni  Ripristina"]
