---
permalink: network/storagegrid-network-types.html 
sidebar: sidebar 
keywords: storagegrid, network types, grid traffic, admin traffic, client traffic, grid network, admin network, client network 
summary: I nodi Grid in un sistema StorageGRID elaborano il traffico Grid, il traffico admin e il traffico client. È necessario configurare la rete in modo appropriato per gestire questi tre tipi di traffico e fornire controllo e sicurezza. 
---
= Tipi di rete StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi della griglia in un sistema StorageGRID elaborano _grid traffic_, _admin traffic_ e _client traffic_. È necessario configurare la rete in modo appropriato per gestire questi tre tipi di traffico e fornire controllo e sicurezza.



== Tipi di traffico

[cols="1a,4a,2a"]
|===
| Tipo di traffico | Descrizione | Tipo di rete 


 a| 
Traffico di rete
 a| 
Il traffico StorageGRID interno che viaggia tra tutti i nodi della griglia. Tutti i nodi della rete devono essere in grado di comunicare con tutti gli altri nodi della rete.
 a| 
Grid Network (obbligatorio)



 a| 
Traffico amministrativo
 a| 
Il traffico utilizzato per l'amministrazione e la manutenzione del sistema.
 a| 
Admin Network (opzionale)



 a| 
Traffico del client
 a| 
Il traffico che viaggia tra le applicazioni client esterne e il grid, incluse tutte le richieste di storage a oggetti dai client S3 e Swift.
 a| 
Rete client (opzionale)

|===
È possibile configurare la rete nei seguenti modi:

* Solo Grid Network
* Reti Grid e Admin
* Reti grid e client
* Reti Grid, Admin e Client


Grid Network è obbligatorio e può gestire tutto il traffico di rete. Le reti Admin e Client possono essere incluse al momento dell'installazione o aggiunte in un secondo momento per adattarsi alle modifiche dei requisiti. Sebbene la rete amministrativa e la rete client siano opzionali, quando si utilizzano queste reti per gestire il traffico amministrativo e client, la rete griglia può essere resa isolata e sicura.



== Interfacce di rete

I nodi StorageGRID sono connessi a ciascuna rete utilizzando le seguenti interfacce specifiche:

|===
| Rete | Nome dell'interfaccia 


 a| 
Grid Network (obbligatorio)
 a| 
eth0



 a| 
Admin Network (opzionale)
 a| 
eth1



 a| 
Rete client (opzionale)
 a| 
eth2

|===
Per ulteriori informazioni sulla mappatura delle porte fisiche o virtuali alle interfacce di rete dei nodi, consultare le istruzioni di installazione.

È necessario configurare quanto segue per ogni rete abilitata su un nodo:

* Indirizzo IP
* Subnet mask
* Indirizzo IP del gateway


È possibile configurare una sola combinazione di indirizzo IP/maschera/gateway per ciascuna delle tre reti su ciascun nodo della griglia. Se non si desidera configurare un gateway per una rete, utilizzare l'indirizzo IP come indirizzo del gateway.

I gruppi ad alta disponibilità (ha) consentono di aggiungere indirizzi IP virtuali all'interfaccia Grid o Client Network. Per ulteriori informazioni, consultare le istruzioni per l'amministrazione di StorageGRID.



== Grid Network

La rete grid è obbligatoria. Viene utilizzato per tutto il traffico StorageGRID interno. Grid Network offre connettività tra tutti i nodi della rete, in tutti i siti e le subnet. Tutti i nodi della rete Grid devono essere in grado di comunicare con tutti gli altri nodi. La rete Grid può essere costituita da più sottoreti. Le reti contenenti servizi grid critici, come NTP, possono essere aggiunte anche come subnet grid.


NOTE: StorageGRID non supporta NAT (Network Address Translation) tra nodi.

La rete Grid può essere utilizzata per tutto il traffico amministrativo e per tutto il traffico client, anche se sono configurate la rete Admin e la rete client. Il gateway Grid Network è il gateway predefinito del nodo, a meno che il nodo non abbia configurato la rete client.


IMPORTANT: Quando si configura Grid Network, è necessario assicurarsi che la rete sia protetta da client non attendibili, ad esempio quelli su Internet.

Tenere presente i seguenti requisiti e dettagli per Grid Network:

* Il gateway Grid Network deve essere configurato se sono presenti più subnet Grid.
* Il gateway Grid Network è il gateway predefinito del nodo fino al completamento della configurazione della griglia.
* Le route statiche vengono generate automaticamente per tutti i nodi a tutte le subnet configurate nell'elenco globale delle subnet di rete Grid.
* Se viene aggiunta una rete client, il gateway predefinito passa dal gateway Grid Network al gateway Client Network una volta completata la configurazione della rete.




== Admin Network (rete amministrativa)

La rete di amministrazione è opzionale. Una volta configurato, può essere utilizzato per l'amministrazione del sistema e il traffico di manutenzione. La rete amministrativa è in genere una rete privata e non deve essere instradabile tra i nodi.

È possibile scegliere i nodi della griglia su cui attivare la rete di amministrazione.

Utilizzando una rete di amministrazione, il traffico amministrativo e di manutenzione non deve viaggiare attraverso la rete di griglia. Gli utilizzi tipici della rete di amministrazione includono l'accesso all'interfaccia utente di Grid Manager, l'accesso a servizi critici come NTP, DNS, gestione delle chiavi esterne (KMS) e Lightweight Directory Access Protocol (LDAP), l'accesso ai registri di controllo sui nodi di amministrazione e l'accesso al protocollo SSH (Secure Shell Protocol) per la manutenzione e il supporto.

La rete amministrativa non viene mai utilizzata per il traffico di rete interno. Viene fornito un gateway Admin Network che consente alla rete di amministrazione di comunicare con più sottoreti esterne. Tuttavia, il gateway Admin Network non viene mai utilizzato come gateway predefinito del nodo.

Tenere presente i seguenti requisiti e dettagli per la rete di amministrazione:

* Il gateway Admin Network è necessario se le connessioni vengono effettuate dall'esterno della subnet Admin Network o se sono configurate più subnet Admin Network.
* Vengono creati percorsi statici per ogni subnet configurata nell'elenco subnet di rete amministrativa del nodo.




== Rete client

La rete client è opzionale. Una volta configurato, viene utilizzato per fornire l'accesso ai servizi grid per le applicazioni client come S3 e Swift. Se si prevede di rendere i dati StorageGRID accessibili a una risorsa esterna (ad esempio, un pool di storage cloud o il servizio di replica di StorageGRID), la risorsa esterna può utilizzare anche la rete client. I nodi Grid possono comunicare con qualsiasi subnet raggiungibile tramite il gateway di rete client.

È possibile scegliere i nodi della griglia su cui deve essere attivata la rete client. Non è necessario che tutti i nodi si trovano sulla stessa rete client e i nodi non comunicheranno mai l'uno con l'altro sulla rete client. La rete client non diventa operativa fino al completamento dell'installazione della griglia.

Per una maggiore sicurezza, è possibile specificare che l'interfaccia di rete client di un nodo sia non attendibile in modo che la rete client sia più restrittiva delle connessioni consentite. Se l'interfaccia Client Network di un nodo non è attendibile, l'interfaccia accetta connessioni in uscita come quelle utilizzate dalla replica di CloudMirror, ma accetta solo connessioni in entrata su porte che sono state configurate esplicitamente come endpoint del bilanciamento del carico. Per ulteriori informazioni sulla funzionalità di rete client non attendibile e sul servizio bilanciamento del carico, consultare le istruzioni per l'amministrazione di StorageGRID.

Quando si utilizza una rete client, il traffico client non deve attraversare la rete griglia. Il traffico Grid Network può essere separato su una rete sicura e non instradabile. I seguenti tipi di nodo sono spesso configurati con una rete client:

* Nodi gateway, perché questi nodi forniscono l'accesso al servizio bilanciamento del carico StorageGRID e all'accesso del client S3 e Swift alla griglia.
* Nodi di storage, perché questi nodi forniscono accesso ai protocolli S3 e Swift, ai Cloud Storage Pools e al servizio di replica CloudMirror.
* Nodi di amministrazione, per garantire che gli utenti tenant possano connettersi a tenant Manager senza dover utilizzare la rete di amministrazione.


Tenere presente quanto segue per la rete client:

* Il gateway di rete client è necessario se la rete client è configurata.
* Una volta completata la configurazione della griglia, il gateway di rete client diventa il percorso predefinito per il nodo della griglia.


.Informazioni correlate
link:networking-requirements-and-guidelines.html["Requisiti e linee guida per il networking"]

link:../admin/index.html["Amministrare StorageGRID"]

link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]

link:../sg6000/index.html["Appliance di storage SG6000"]

link:../sg5700/index.html["Appliance di storage SG5700"]

link:../rhel/index.html["Installare Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Installare Ubuntu o Debian"]

link:../vmware/index.html["Installare VMware"]
