---
permalink: network/storagegrid-networking-overview.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: La configurazione della rete per un sistema StorageGRID richiede un livello elevato di esperienza con switch Ethernet, reti TCP/IP, subnet, routing di rete e firewall. 
---
= Panoramica delle reti StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configurazione della rete per un sistema StorageGRID richiede un livello elevato di esperienza con switch Ethernet, reti TCP/IP, subnet, routing di rete e firewall.

Prima di configurare il networking, acquisire familiarità con l'architettura StorageGRID come descritto nella sezione _Grid primer_.

Prima di implementare e configurare StorageGRID, è necessario configurare l'infrastruttura di rete. La comunicazione deve avvenire tra tutti i nodi del grid e tra il grid e i client e i servizi esterni.

I client esterni e i servizi esterni devono connettersi alle reti StorageGRID per eseguire le seguenti funzioni:

* Memorizzare e recuperare i dati degli oggetti
* Ricevi notifiche via email
* Accedere all'interfaccia di gestione di StorageGRID (il gestore di griglia e il gestore dei tenant)
* Accesso alla condivisione dell'audit (opzionale)
* Fornire servizi come:
+
** NTP (Network Time Protocol)
** DNS (Domain Name System)
** Server di gestione delle chiavi (KMS)




La rete StorageGRID deve essere configurata in modo appropriato per gestire il traffico per queste funzioni e altro ancora.

Dopo aver stabilito quale delle tre reti StorageGRID si desidera utilizzare e come configurarle, è possibile installare e configurare i nodi StorageGRID seguendo le istruzioni appropriate.

.Informazioni correlate
link:../primer/index.html["Primer griglia"]

link:../admin/index.html["Amministrare StorageGRID"]

link:../release-notes/index.html["Note di rilascio"]

link:../rhel/index.html["Installare Red Hat Enterprise Linux o CentOS"]

link:../ubuntu/index.html["Installare Ubuntu o Debian"]

link:../vmware/index.html["Installare VMware"]

link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]

link:../sg6000/index.html["Appliance di storage SG6000"]

link:../sg5700/index.html["Appliance di storage SG5700"]

link:../sg5600/index.html["Appliance di storage SG5600"]
