---
permalink: sg5600/installing-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, install, installing 
summary: 'L"installazione dell"hardware include diverse attività importanti, tra cui l"installazione di componenti hardware, il cablaggio di tali componenti e la configurazione delle porte.' 
---
= Installazione dell'hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installazione dell'hardware include diverse attività importanti, tra cui l'installazione di componenti hardware, il cablaggio di tali componenti e la configurazione delle porte.

.Fasi
* link:registering-hardware.html["Registrazione dell'hardware"]
* link:installing-appliance-in-cabinet-or-rack-sg5600.html["Installazione dell'appliance in un cabinet o rack (SG5600)"]
* link:cabling-appliance-sg5600.html["Cablaggio dell'appliance (SG5600)"]
* link:connecting-ac-power-cords-sg5600.html["Collegamento dei cavi di alimentazione CA (SG5600)"]
* link:turning-power-on-sg5600.html["Accensione (SG5600)"]
* link:viewing-boot-up-status-and-reviewing-error-codes-on-sg5600-controllers.html["Visualizzazione dello stato di avvio e revisione dei codici di errore sui controller SG5600"]

