---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: StorageGRID, tenant manager, tenant group, duplicating tenant group, duplicate tenant group 
summary: È possibile creare nuovi gruppi più rapidamente duplicando un gruppo esistente. 
---
= Duplicazione di un gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare nuovi gruppi più rapidamente duplicando un gruppo esistente.

.Di cosa hai bisogno
* È necessario accedere a tenant Manager utilizzando un browser supportato.
* È necessario appartenere a un gruppo di utenti che dispone dell'autorizzazione di accesso root.


.Fasi
. Selezionare *GESTIONE ACCESSI* > *gruppi*.
. Selezionare la casella di controllo relativa al gruppo che si desidera duplicare.
. Selezionare *Duplica gruppo*. Per ulteriori dettagli sulla creazione di un gruppo, consulta le istruzioni per la creazione di gruppi per un tenant S3 o Swift.
. Selezionare la scheda *Local group* (Gruppo locale) per creare un gruppo locale oppure la scheda *Federated group* (Gruppo federato) per importare un gruppo dall'origine dell'identità precedentemente configurata.
+
Se è attivato il Single Sign-on (SSO) per il sistema StorageGRID, gli utenti appartenenti a gruppi locali non potranno accedere a Gestione tenant, anche se possono utilizzare le applicazioni client per gestire le risorse del tenant, in base alle autorizzazioni di gruppo.

. Inserire il nome del gruppo.
+
** *Local group* (Gruppo locale): Immettere un nome visualizzato e un nome univoco. È possibile modificare il nome visualizzato in un secondo momento.
** *Federated group*: Immettere il nome univoco. Per Active Directory, il nome univoco è il nome associato a `sAMAccountName` attributo. Per OpenLDAP, il nome univoco è il nome associato a `uid` attributo.


. Selezionare *continua*.
. Se necessario, modificare le autorizzazioni per questo gruppo.
. Selezionare *continua*.
. Se si desidera duplicare un gruppo per un tenant S3, selezionare un criterio diverso dai pulsanti di opzione *Add S3 policy* (Aggiungi criterio S3). Se è stato selezionato un criterio personalizzato, aggiornare la stringa JSON come richiesto.
. Selezionare *Crea gruppo*.


.Informazioni correlate
link:creating-groups-for-s3-tenant.html["Creazione di gruppi per un tenant S3"]

link:creating-groups-for-swift-tenant.html["Creazione di gruppi per un tenant Swift"]

link:tenant-management-permissions.html["Permessi di gestione del tenant"]
