---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords:  
summary: Prima di installare StorageGRID, è necessario raccogliere e preparare il materiale necessario. 
---
= Materiali richiesti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare StorageGRID, è necessario raccogliere e preparare il materiale necessario.

[cols="1a,2a"]
|===
| Elemento | Note 


 a| 
Licenza NetApp StorageGRID
 a| 
È necessario disporre di una licenza NetApp valida con firma digitale.

*Nota*: L'archivio di installazione di StorageGRID include una licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



 a| 
Archivio di installazione StorageGRID per VMware
 a| 
È necessario scaricare l'archivio di installazione di StorageGRID ed estrarre i file.



 a| 
Software e documentazione VMware
 a| 
Durante l'installazione, i nodi virtual grid vengono implementati su macchine virtuali in VMware vSphere Web Client. Per le versioni supportate, vedere la matrice di interoperabilità.



 a| 
Laptop di assistenza
 a| 
Il sistema StorageGRID viene installato tramite un taglioIl laptop di assistenza deve disporre di:

* Porta di rete
* Client SSH (ad esempio, putty)
* Browser Web supportato




 a| 
Documentazione StorageGRID
 a| 
* Note di rilascio
* Istruzioni per l'amministrazione di StorageGRID


|===
.Informazioni correlate
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]

link:downloading-and-extracting-storagegrid-installation-files.html["Download ed estrazione dei file di installazione di StorageGRID"]

link:web-browser-requirements.html["Requisiti del browser Web"]

link:../admin/index.html["Amministrare StorageGRID"]

link:../release-notes/index.html["Note di rilascio"]
