---
permalink: vmware/virtual-machine-resource-reservation-requires-adjustment.html 
sidebar: sidebar 
keywords:  
summary: I file OVF includono una riserva di risorse progettata per garantire che ciascun nodo di griglia disponga di RAM e CPU sufficienti per funzionare in modo efficiente. Se si creano macchine virtuali implementando questi file OVF su VMware e il numero predefinito di risorse non è disponibile, le macchine virtuali non si avviano. 
---
= La prenotazione delle risorse delle macchine virtuali richiede una modifica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I file OVF includono una riserva di risorse progettata per garantire che ciascun nodo di griglia disponga di RAM e CPU sufficienti per funzionare in modo efficiente. Se si creano macchine virtuali implementando questi file OVF su VMware e il numero predefinito di risorse non è disponibile, le macchine virtuali non si avviano.

.A proposito di questa attività
Se si è certi che l'host della macchina virtuale disponga di risorse sufficienti per ciascun nodo della griglia, regolare manualmente le risorse allocate per ciascuna macchina virtuale, quindi provare ad avviare le macchine virtuali.

.Fasi
. Nell'albero del client di VMware vSphere Hypervisor, selezionare la macchina virtuale non avviata.
. Fare clic con il pulsante destro del mouse sulla macchina virtuale e selezionare *Edit Settings* (Modifica impostazioni).‐
. Dalla finestra Virtual Machines Properties (Proprietà macchine virtuali), selezionare la scheda *Resources* (risorse).
. Regolare le risorse allocate alla macchina virtuale:
+
.. Selezionare *CPU*, quindi utilizzare il dispositivo di scorrimento Reservation (prenotazione) per regolare i MHz riservati per questa macchina virtuale.
.. Selezionare *memoria*, quindi utilizzare il dispositivo di scorrimento prenotazione per regolare il MB riservato per questa macchina virtuale.


. Fare clic su *OK*.
. Ripetere la procedura secondo necessità per altre macchine virtuali ospitate sullo stesso host di macchine virtuali.

