---
permalink: rhel/installation-overview.html 
sidebar: sidebar 
keywords: storagegrid, rhel installation, redhat installation, redhat linux, centos installation 
summary: 'L"installazione di un sistema StorageGRID in un ambiente Linux Red Hat Enterprise include tre passaggi principali.' 
---
= Panoramica dell'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installazione di un sistema StorageGRID in un ambiente Red Hat Enterprise Linux (RHEL) o CentOS Linux include tre passaggi principali.

. *Preparazione*: Durante la pianificazione e la preparazione, si eseguono le seguenti attività:
+
** Scopri i requisiti hardware e storage per StorageGRID.
** Scopri le specifiche del networking StorageGRID per configurare la rete in modo appropriato. Per ulteriori informazioni, consultare le linee guida per il collegamento in rete di StorageGRID.
** Identificare e preparare i server fisici o virtuali che si intende utilizzare per ospitare i nodi grid StorageGRID.
** Sui server preparati:
+
*** Installare Linux
*** Configurare la rete host
*** Configurare lo storage host
*** Installare Docker
*** Installare i servizi host di StorageGRID




. *Implementazione*: Implementare i nodi grid utilizzando l'interfaccia utente appropriata. Quando si implementano nodi grid, questi vengono creati come parte del sistema StorageGRID e connessi a una o più reti.
+
.. Utilizzare la riga di comando di Linux e i file di configurazione dei nodi per implementare i nodi grid basati su software sugli host preparati al punto 1.
.. Utilizzare il programma di installazione dell'appliance StorageGRID per implementare i nodi dell'appliance StorageGRID.
+

NOTE: Le istruzioni di installazione e integrazione specifiche dell'hardware non sono incluse nella procedura di installazione di StorageGRID. Per informazioni su come installare le appliance StorageGRID, consultare le istruzioni di installazione e manutenzione dell'appliance.



. *Configurazione*: Una volta implementati tutti i nodi, utilizzare StorageGRIDGrid Manager per configurare la griglia e completare l'installazione.


Queste istruzioni consigliano un approccio standard per l'implementazione e la configurazione di un sistema StorageGRID. Vedere anche le informazioni sui seguenti approcci alternativi:

* Utilizza un framework di orchestrazione standard come Ansible, Puppet o Chef per installare RHEL o CentOS, configurare networking e storage, installare Docker e il servizio host StorageGRID e implementare nodi virtual grid.
* Automatizzare la distribuzione e la configurazione del sistema StorageGRID utilizzando uno script di configurazione Python (fornito nell'archivio di installazione).
* Automatizza l'implementazione e la configurazione dei nodi grid dell'appliance con uno script di configurazione Python (disponibile dall'archivio di installazione o dal programma di installazione dell'appliance StorageGRID).
* Se sei uno sviluppatore avanzato di implementazioni StorageGRID, utilizza le API REST di installazione per automatizzare l'installazione dei nodi grid StorageGRID.


.Informazioni correlate
link:planning-and-preparation.html["Pianificazione e preparazione"]

link:deploying-virtual-grid-nodes.html["Implementazione di nodi virtual grid"]

link:configuring-grid-and-completing-installation.html["Configurazione della griglia e completamento dell'installazione"]

link:automating-installation.html["Automazione dell'installazione"]

link:overview-of-installation-rest-api.html["Panoramica dell'API REST per l'installazione"]

link:../network/index.html["Linee guida per la rete"]
