---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords:  
summary: Gli utenti locali di Grid Manager possono modificare la propria password. 
---
= Modifica della password
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli utenti locali di Grid Manager possono modificare la propria password.

.Di cosa hai bisogno
È necessario accedere a Grid Manager utilizzando un browser supportato.

.A proposito di questa attività
Se si effettua l'accesso a StorageGRID come utente federato o se è attivato il Single Sign-on (SSO), non è possibile modificare la password in Grid Manager. È invece necessario modificare la password nell'origine dell'identità esterna, ad esempio Active Directory o OpenLDAP.

.Fasi
. Dall'intestazione Grid Manager, selezionare *_nome_Modifica password*.
. Inserire la password corrente.
. Digitare una nuova password.
+
La password deve contenere almeno 8 e non più di 32 caratteri. Le password distinguono tra maiuscole e minuscole.

. Immettere nuovamente la nuova password.
. Fare clic su *Save* (Salva).

