---
permalink: admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords:  
summary: È possibile sostituire il certificato del server StorageGRID predefinito con un singolo certificato server personalizzato che consente agli utenti di accedere a Grid Manager e a Tenant Manager senza incontrare avvisi di sicurezza. 
---
= Configurazione di un certificato server personalizzato per Grid Manager e Tenant Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire il certificato del server StorageGRID predefinito con un singolo certificato server personalizzato che consente agli utenti di accedere a Grid Manager e a Tenant Manager senza incontrare avvisi di sicurezza.

.A proposito di questa attività
Per impostazione predefinita, ogni nodo amministrativo riceve un certificato firmato dalla CA della griglia. Questi certificati firmati dalla CA possono essere sostituiti da un singolo certificato server personalizzato comune e dalla chiave privata corrispondente.

Poiché per tutti i nodi di amministrazione viene utilizzato un singolo certificato server personalizzato, è necessario specificare il certificato come carattere jolly o certificato multidominio se i client devono verificare il nome host durante la connessione a Grid Manager e Tenant Manager. Definire il certificato personalizzato in modo che corrisponda a tutti i nodi Admin nella griglia.

È necessario completare la configurazione sul server e, a seconda dell'autorità di certificazione (CA) di origine in uso, gli utenti potrebbero dover installare il certificato CA di origine nel browser Web utilizzato per accedere a Grid Manager e a Tenant Manager.


NOTE: Per garantire che le operazioni non vengano interrotte da un certificato del server guasto, l'avviso *scadenza del certificato del server per l'interfaccia di gestione* e l'allarme MCEP (Management Interface Certificate Expiry) legacy vengono attivati quando il certificato del server sta per scadere. In base alle esigenze, è possibile visualizzare il numero di giorni che devono essere trascorsi prima della scadenza del certificato di servizio corrente selezionando *supporto* *Strumenti* *topologia griglia*. Quindi, selezionare *_Primary Admin Node_* *CMN* *Resources*.

[NOTE]
====
Se si accede a Grid Manager o Tenant Manager utilizzando un nome di dominio invece di un indirizzo IP, il browser mostra un errore di certificato senza l'opzione di ignorare se si verifica una delle seguenti condizioni:

* Il certificato del server dell'interfaccia di gestione personalizzata scade.
* Viene ripristinato il certificato del server di un'interfaccia di gestione personalizzata al certificato del server predefinito.


====
.Fasi
. Selezionare *Configurazione* *Impostazioni di rete* *certificati server*.
. Nella sezione Management Interface Server Certificate (certificato server interfaccia di gestione), fare clic su *Install Custom Certificate* (Installa certificato personalizzato).
. Caricare i file dei certificati del server richiesti:
+
** *Server Certificate*: Il file di certificato del server personalizzato (`.crt`).
** *Server Certificate Private Key* (chiave privata certificato server): Il file di chiave privata del certificato del server personalizzato (`.key`).
+

NOTE: Le chiavi private EC devono essere 224 bit o superiori. Le chiavi private RSA devono essere 2048 bit o superiori.

** *Bundle CA*: Un singolo file contenente i certificati di ciascuna CA intermedia. Il file deve contenere ciascuno dei file di certificato CA con codifica PEM, concatenati in ordine di catena del certificato.


. Fare clic su *Save* (Salva).
+
I certificati server personalizzati vengono utilizzati per tutte le nuove connessioni client successive.

+
Selezionare una scheda per visualizzare informazioni dettagliate sul certificato del server StorageGRID predefinito o su un certificato firmato dalla CA caricato.

+

NOTE: Dopo aver caricato un nuovo certificato, attendere fino a un giorno per eliminare eventuali avvisi relativi alla scadenza del certificato (o allarmi legacy).

. Aggiornare la pagina per assicurarsi che il browser Web sia aggiornato.

