---
permalink: admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: 'Quando è attivato il single sign-on, gli utenti possono accedere a Grid Manager, Tenant Manager, Grid Management API o tenant Management API solo se le loro credenziali sono autorizzate utilizzando il processo di accesso SSO implementato dall"organizzazione.' 
---
= Configurazione del single sign-on
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando è attivato il Single Sign-on (SSO), gli utenti possono accedere a Grid Manager, Tenant Manager, Grid Management API o tenant Management API solo se le loro credenziali sono autorizzate utilizzando il processo di accesso SSO implementato dall'organizzazione.

* link:confirming-federated-users-can-sign-in.html["Conferma che gli utenti federati possono effettuare l'accesso"]
* link:using-sandbox-mode.html["Utilizzo della modalità sandbox"]
* link:creating-relying-party-trusts-in-ad-fs.html["Creazione di trust per la parte di base in ad FS"]
* link:testing-relying-party-trusts.html["Verifica dei trust della parte di base"]
* link:enabling-single-sign-on.html["Abilitazione del single sign-on"]
* link:disabling-single-sign-on.html["Disattivazione del single sign-on"]
* link:temporarily-disabling-and-reenabling-sso-for-admin-node.html["Disattivare e riabilitare temporaneamente il Single Sign-on per un nodo di amministrazione"]

