---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords:  
summary: 'Man mano che i nodi di storage raggiungono la capacità, è necessario espandere il sistema StorageGRID con l"aggiunta di nuovo storage. Sono disponibili tre opzioni: Aggiunta di volumi di storage, aggiunta di shelf di espansione dello storage e aggiunta di nodi di storage.' 
---
= Gestione dei nodi di storage completi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Man mano che i nodi di storage raggiungono la capacità, è necessario espandere il sistema StorageGRID con l'aggiunta di nuovo storage. Sono disponibili tre opzioni: Aggiunta di volumi di storage, aggiunta di shelf di espansione dello storage e aggiunta di nodi di storage.



== Aggiunta di volumi di storage

Ciascun nodo di storage supporta un numero massimo di volumi di storage. Il valore massimo definito varia in base alla piattaforma. Se un nodo di storage contiene meno del numero massimo di volumi di storage, è possibile aggiungere volumi per aumentarne la capacità. Consultare le istruzioni per espandere un sistema StorageGRID.



== Aggiunta di shelf di espansione dello storage

Alcuni nodi storage dell'appliance StorageGRID, come SG6060, possono supportare shelf di storage aggiuntivi. Se si dispone di appliance StorageGRID con funzionalità di espansione che non sono già state estese alla capacità massima, è possibile aggiungere shelf di storage per aumentare la capacità. Consultare le istruzioni per espandere un sistema StorageGRID.



== Aggiunta di nodi di storage

È possibile aumentare la capacità dello storage aggiungendo nodi di storage. Quando si aggiunge lo storage, è necessario prendere in considerazione le regole ILM attualmente attive e i requisiti di capacità. Consultare le istruzioni per espandere un sistema StorageGRID.

.Informazioni correlate
link:../expand/index.html["Espandi il tuo grid"]
