---
permalink: admin/monitoring-data-migration.html 
sidebar: sidebar 
keywords:  
summary: La migrazione dei dati deve essere monitorata e regolata in base alle necessità per garantire che i dati vengano inseriti in base alla policy ILM entro i tempi richiesti. 
---
= Monitoraggio della migrazione dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La migrazione dei dati deve essere monitorata e regolata in base alle necessità per garantire che i dati vengano inseriti in base alla policy ILM entro i tempi richiesti.

Questa tabella elenca gli attributi da monitorare durante la migrazione dei dati e i problemi che rappresentano.

Se si utilizzano criteri di classificazione del traffico con limiti di velocità per accelerare l'acquisizione, è possibile monitorare la velocità osservata insieme alle statistiche descritte nella tabella seguente e ridurre i limiti, se necessario.

[cols="1a,2a"]
|===
| Monitorare | Descrizione 


 a| 
Numero di oggetti in attesa di valutazione ILM
 a| 
. Selezionare *supporto* > *Strumenti* > *topologia griglia*.
. Selezionare *_Deployment_* *Overview* *Main*.
. Nella sezione ILM Activity (attività ILM), monitorare il numero di oggetti visualizzati per i seguenti attributi:
+
** *In attesa - tutti (XQUZ)*: Il numero totale di oggetti in attesa di valutazione ILM.
** *In attesa - Client (XCQZ)*: Il numero totale di oggetti in attesa di valutazione ILM dalle operazioni del client (ad esempio, acquisizione).


. Se il numero di oggetti visualizzato per uno di questi attributi supera 100,000, ridurre il tasso di acquisizione degli oggetti per ridurre il carico sul sistema StorageGRID.




 a| 
Capacità di storage del sistema di archiviazione mirato
 a| 
Se la policy ILM salva una copia dei dati migrati in un sistema storage di archiviazione di destinazione (nastro o cloud), monitorate la capacità del sistema storage di archiviazione di destinazione per garantire che vi sia una capacità sufficiente per i dati migrati.



 a| 
*Nodo di archivio* *ARC* *Memorizza*
 a| 
Se viene attivato un allarme per l'attributo *Store Failures (ARVF)*, il sistema storage di archiviazione di destinazione potrebbe aver raggiunto la capacità. Controllare il sistema storage di archiviazione di destinazione e risolvere eventuali problemi che hanno generato un allarme.

|===