---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts, reference 
summary: La tabella seguente elenca tutti gli avvisi StorageGRID predefiniti. Se necessario, è possibile creare regole di avviso personalizzate per adattarsi al proprio approccio di gestione del sistema. 
---
= Riferimenti agli avvisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La tabella seguente elenca tutti gli avvisi StorageGRID predefiniti. Se necessario, è possibile creare regole di avviso personalizzate per adattarsi al proprio approccio di gestione del sistema.

Per informazioni sulle metriche utilizzate in alcuni di questi avvisi, consulta le informazioni sulle metriche Prometheus più comunemente utilizzate.

|===
| Nome dell'avviso | Descrizione e azioni consigliate 


 a| 
Batteria dell'appliance scaduta
 a| 
La batteria del controller di storage dell'appliance è scaduta.

. Sostituire la batteria. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Batteria dell'appliance guasta
 a| 
La batteria del controller di storage dell'appliance si è guastata.

. Sostituire la batteria. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
La capacità appresa della batteria dell'appliance non è sufficiente
 a| 
La capacità appresa della batteria nel controller di storage dell'appliance non è sufficiente.

. Sostituire la batteria. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Batteria dell'apparecchio quasi scaduta
 a| 
La batteria del controller di storage dell'appliance sta per scadere.

. Sostituire la batteria al più presto. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Batteria dell'apparecchio rimossa
 a| 
La batteria nel controller di storage dell'appliance non è presente.

. Installare una batteria. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Batteria dell'apparecchio troppo calda
 a| 
La batteria del controller di storage dell'apparecchio è surriscaldata.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Esaminare i possibili motivi dell'aumento della temperatura, ad esempio un guasto alla ventola o all'HVAC.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Errore di comunicazione BMC dell'appliance
 a| 
La comunicazione con il BMC (Baseboard Management Controller) è stata persa.

. Verificare che il BMC funzioni correttamente. Selezionare *Nodes*, quindi selezionare la scheda *hardware* per il nodo dell'appliance. Individuare il campo Compute Controller BMC IP (IP BMC controller di calcolo) e individuare l'IP desiderato.
. Tentare di ripristinare le comunicazioni BMC posizionando il nodo in modalità di manutenzione, quindi spegnendo e riaccendendo l'appliance. Consultare le istruzioni di installazione e manutenzione dell'apparecchio.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Periferica di backup della cache dell'appliance non riuscita
 a| 
Si è verificato un errore in una periferica di backup della cache persistente.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Contattare il supporto tecnico.




 a| 
Capacità insufficiente del dispositivo di backup della cache dell'appliance
 a| 
Capacità periferica di backup della cache insufficiente.contattare il supporto tecnico.



 a| 
Dispositivo di backup cache dell'appliance protetto da scrittura
 a| 
Una periferica di backup della cache è protetta da scrittura.contattare il supporto tecnico.



 a| 
Mancata corrispondenza delle dimensioni della memoria cache dell'appliance
 a| 
I due controller dell'appliance hanno diverse dimensioni della cache.contattare il supporto tecnico.



 a| 
Temperatura dello chassis del controller di calcolo dell'appliance troppo alta
 a| 
La temperatura del controller di calcolo in un'appliance StorageGRID ha superato una soglia nominale.

. Verificare l'eventuale presenza di condizioni di surriscaldamento dei componenti hardware e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Temperatura CPU del controller di calcolo dell'appliance troppo alta
 a| 
La temperatura della CPU nel controller di calcolo di un'appliance StorageGRID ha superato una soglia nominale.

. Verificare l'eventuale presenza di condizioni di surriscaldamento dei componenti hardware e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Il controller di calcolo dell'appliance richiede attenzione
 a| 
È stato rilevato un guasto hardware nel controller di calcolo di un'appliance StorageGRID.

. Verificare la presenza di errori nei componenti hardware e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Si è verificato un problema nell'alimentatore A del controller di calcolo dell'appliance
 a| 
Si è verificato un problema nell'alimentatore A del controller di calcolo. Questo avviso potrebbe indicare che l'alimentatore è guasto o che si è verificato un problema nell'alimentazione.

. Verificare la presenza di errori nei componenti hardware e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Si è verificato un problema nell'alimentatore B del controller di calcolo dell'appliance
 a| 
Si è verificato un problema nell'alimentatore B del controller di calcolo. Questo avviso potrebbe indicare che l'alimentatore è guasto o che si è verificato un problema di alimentazione.

. Verificare la presenza di errori nei componenti hardware e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Il servizio di monitoraggio dell'hardware di calcolo dell'appliance si è bloccato
 a| 
Il servizio che monitora lo stato dell'hardware dello storage ha smesso di riportare i dati.

. Controllare lo stato del servizio di stato del sistema eos nel sistema operativo di base.
. Se il servizio si trova in uno stato di arresto o di errore, riavviarlo.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Rilevato guasto nel Fibre Channel dell'appliance
 a| 
Si è verificato un problema con la connessione Fibre Channel tra lo storage e i controller di calcolo nell'appliance.

. Verificare la presenza di errori nei componenti hardware (*nodi* *_nodo appliance_* *hardware*). Se lo stato di uno dei componenti non è "`nominale`", eseguire le seguenti operazioni:
+
.. Verificare che i cavi Fibre Channel tra i controller siano collegati correttamente.
.. Assicurarsi che i cavi Fibre Channel siano privi di piegature eccessive.
.. Verificare che i moduli SFP+ siano inseriti correttamente.




*Nota:* se il problema persiste, il sistema StorageGRID potrebbe disattivare automaticamente la connessione problematica.

. Se necessario, sostituire i componenti. Consultare le istruzioni di installazione e manutenzione dell'apparecchio.




 a| 
Errore della porta HBA Fibre Channel dell'appliance
 a| 
Una porta HBA Fibre Channel si sta guastando o si è guastata.contattare il supporto tecnico.



 a| 
Unità flash cache dell'appliance non ottimali
 a| 
I dischi utilizzati per la cache SSD non sono ottimali.

. Sostituire le unità cache SSD. Consultare le istruzioni di installazione e manutenzione dell'apparecchio.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Interconnessione dell'appliance/contenitore della batteria rimosso
 a| 
Il contenitore di interconnessione/batteria non è presente.

. Sostituire la batteria. La procedura per la sostituzione di un controller di storage è inclusa nelle istruzioni di installazione e manutenzione dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]


. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Porta LACP dell'appliance mancante
 a| 
Una porta su un'appliance StorageGRID non partecipa al bond LACP.

. Controllare la configurazione dello switch. Assicurarsi che l'interfaccia sia configurata nel gruppo di aggregazione dei collegamenti corretto.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Alimentatore generale dell'appliance degradato
 a| 
La potenza di un'appliance StorageGRID è diversa dalla tensione di esercizio consigliata.

. Controllare lo stato degli alimentatori A e B per determinare quale alimentatore funziona in modo anomalo e seguire le azioni consigliate:
+
** Se si dispone di SG100, SG1000 o SG6000, utilizzare BMC.
** Se si dispone di un sistema SG5600 o SG5700, utilizzare Gestore di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]






 a| 
Guasto del controller dello storage dell'appliance A.
 a| 
Si è verificato un errore nel controller storage A di un'appliance StorageGRID.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Guasto del controller storage dell'appliance B.
 a| 
Il controller dello storage B in un'appliance StorageGRID si è guastato.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Guasto al disco del controller dello storage dell'appliance
 a| 
Uno o più dischi di un'appliance StorageGRID si sono guastati o non sono ottimali.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Problema hardware del controller dello storage dell'appliance
 a| 
Il software SANtricity segnala "richiede attenzione" per un componente di un'appliance StorageGRID.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Guasto all'alimentazione Del controller dello storage dell'appliance A.
 a| 
L'alimentazione A di un'appliance StorageGRID non è conforme alla tensione di esercizio consigliata.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Guasto all'alimentazione B del controller storage dell'appliance
 a| 
L'alimentazione B di un apparecchio StorageGRID non è conforme alla tensione di esercizio consigliata.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Il servizio di monitoraggio hardware dello storage dell'appliance si è bloccato
 a| 
Il servizio che monitora lo stato dell'hardware dello storage ha smesso di riportare i dati.

. Controllare lo stato del servizio di stato del sistema eos nel sistema operativo di base.
. Se il servizio si trova in uno stato di arresto o di errore, riavviarlo.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Gli shelf di storage delle appliance sono degradati
 a| 
Lo stato di uno dei componenti dello shelf di storage di un'appliance di storage è degradato.

. Utilizzare Gestione di sistema di SANtricity per controllare i componenti hardware e seguire le azioni consigliate.
. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance:
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Temperatura dell'apparecchio superata
 a| 
La temperatura nominale o massima del controller di storage dell'appliance è stata superata.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Esaminare i possibili motivi dell'aumento della temperatura, ad esempio un guasto alla ventola o all'HVAC.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Sensore di temperatura dell'apparecchio rimosso
 a| 
È stato rimosso un sensore di temperatura. Contattare il supporto tecnico.



 a| 
Errore compattatore automatico Cassandra
 a| 
Si è verificato un errore nel compattatore automatico Cassandra. Il compattatore automatico Cassandra è presente su tutti i nodi di storage e gestisce le dimensioni del database Cassandra per la sovrascrittura e l'eliminazione di carichi di lavoro pesanti. Anche se questa condizione persiste, alcuni carichi di lavoro sperimenteranno un consumo inaspettatamente elevato di metadati.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Contattare il supporto tecnico.




 a| 
Metriche del compattatore automatico Cassandra non aggiornate
 a| 
Le metriche che descrivono il compattatore automatico Cassandra non sono aggiornate. Il compattatore automatico Cassandra è presente su tutti i nodi di storage e gestisce le dimensioni del database Cassandra per la sovrascrittura e l'eliminazione di carichi di lavoro pesanti. Mentre questo avviso persiste, alcuni carichi di lavoro sperimenteranno un consumo inaspettatamente elevato di metadati.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Contattare il supporto tecnico.




 a| 
Errore di comunicazione Cassandra
 a| 
I nodi che eseguono il servizio Cassandra hanno problemi di comunicazione tra loro.questo avviso indica che qualcosa sta interferendo con le comunicazioni da nodo a nodo. Potrebbe esserci un problema di rete o il servizio Cassandra potrebbe essere inattivo su uno o più nodi di storage.

. Determinare se è presente un altro avviso che interessa uno o più nodi di storage. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Verificare la presenza di un problema di rete che potrebbe interessare uno o più nodi di storage.
. Selezionare *supporto* > *Strumenti* > *topologia griglia*.
. Per ciascun nodo di storage del sistema, selezionare *SSM* *servizi*. Assicurarsi che lo stato del servizio Cassandra sia "` in esecuzione`".
. Se Cassandra non è in esecuzione, seguire la procedura per avviare o riavviare un servizio nelle istruzioni di ripristino e manutenzione.
. Se tutte le istanze del servizio Cassandra sono in esecuzione e l'avviso non viene risolto, contattare il supporto tecnico.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Le compaction di Cassandra sono sovraccaricate
 a| 
Il processo di compattazione Cassandra è sovraccarico.se il processo di compattazione è sovraccarico, le prestazioni di lettura potrebbero peggiorare e la RAM potrebbe essere consuicata. Anche il servizio Cassandra potrebbe non rispondere o bloccarsi.

. Riavviare il servizio Cassandra seguendo la procedura per riavviare un servizio nelle istruzioni di ripristino e manutenzione.
. Se l'avviso persiste, contattare il supporto tecnico.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Metriche di riparazione Cassandra non aggiornate
 a| 
Le metriche che descrivono i lavori di riparazione Cassandra non sono aggiornate. Se questa condizione persiste per più di 48 ore, le query del client, come gli elenchi dei bucket, potrebbero mostrare i dati cancellati.

. Riavviare il nodo. Da Grid Manager, selezionare *Nodes*, selezionare il nodo e selezionare la scheda Tasks (attività).
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Il processo di riparazione di Cassandra è lento
 a| 
Il progresso delle riparazioni del database Cassandra è lento.quando le riparazioni del database sono lente, le operazioni di coerenza dei dati Cassandra sono ostacolate. Se questa condizione persiste per più di 48 ore, le query del client, come gli elenchi dei bucket, potrebbero mostrare i dati cancellati.

. Verificare che tutti i nodi di storage siano online e che non siano presenti avvisi relativi alla rete.
. Monitorare questo avviso per un massimo di 2 giorni per verificare se il problema si risolve da solo.
. Se le riparazioni del database continuano a procedere lentamente, contattare il supporto tecnico.




 a| 
Servizio di riparazione Cassandra non disponibile
 a| 
Il servizio di riparazione Cassandra non è disponibile. Il servizio di riparazione Cassandra esiste su tutti i nodi di storage e fornisce funzioni di riparazione critiche per il database Cassandra. Se questa condizione persiste per più di 48 ore, le query del client, come gli elenchi dei bucket, potrebbero mostrare i dati cancellati.

. Selezionare *supporto* > *Strumenti* > *topologia griglia*.
. Per ciascun nodo di storage del sistema, selezionare *SSM* *servizi*. Assicurarsi che lo stato del servizio Cassandra Reaper sia "in esecuzione".
. Se Cassandra Reaper non è in esecuzione, seguire la procedura per avviare o riavviare un servizio nelle istruzioni di ripristino e manutenzione.
. Se tutte le istanze del servizio Cassandra Reaper sono in esecuzione e l'avviso non viene risolto, contattare il supporto tecnico.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Errore di connettività del pool di cloud storage
 a| 
Il controllo dello stato di salute dei Cloud Storage Pools ha rilevato uno o più nuovi errori.

. Accedere alla sezione Cloud Storage Pools della pagina Storage Pools.
. Esaminare la colonna Last Error (ultimo errore) per determinare quale pool di storage cloud presenta un errore.
. Consultare le istruzioni per la gestione degli oggetti con la gestione del ciclo di vita delle informazioni.


link:../ilm/index.html["Gestire gli oggetti con ILM"]



 a| 
Lease DHCP scaduto
 a| 
Il lease DHCP su un'interfaccia di rete è scaduto.se il lease DHCP è scaduto, seguire le azioni consigliate:

. Assicurarsi che vi sia connettività tra questo nodo e il server DHCP sull'interfaccia interessata.
. Assicurarsi che siano disponibili indirizzi IP da assegnare nella subnet interessata sul server DHCP.
. Assicurarsi che vi sia una prenotazione permanente per l'indirizzo IP configurato nel server DHCP. In alternativa, utilizzare lo strumento Modifica IP StorageGRID per assegnare un indirizzo IP statico esterno al pool di indirizzi DHCP. Consultare le istruzioni di ripristino e manutenzione.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Il lease DHCP sta per scadere
 a| 
Il lease DHCP su un'interfaccia di rete sta per scadere.per evitare la scadenza del lease DHCP, seguire le azioni consigliate:

. Assicurarsi che vi sia connettività tra questo nodo e il server DHCP sull'interfaccia interessata.
. Assicurarsi che siano disponibili indirizzi IP da assegnare nella subnet interessata sul server DHCP.
. Assicurarsi che vi sia una prenotazione permanente per l'indirizzo IP configurato nel server DHCP. In alternativa, utilizzare lo strumento Modifica IP StorageGRID per assegnare un indirizzo IP statico esterno al pool di indirizzi DHCP. Consultare le istruzioni di ripristino e manutenzione.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Server DHCP non disponibile
 a| 
Il server DHCP non è disponibile.il nodo StorageGRID non è in grado di contattare il server DHCP. Il lease DHCP per l'indirizzo IP del nodo non può essere validato.

. Assicurarsi che vi sia connettività tra questo nodo e il server DHCP sull'interfaccia interessata.
. Assicurarsi che siano disponibili indirizzi IP da assegnare nella subnet interessata sul server DHCP.
. Assicurarsi che vi sia una prenotazione permanente per l'indirizzo IP configurato nel server DHCP. In alternativa, utilizzare lo strumento Modifica IP StorageGRID per assegnare un indirizzo IP statico esterno al pool di indirizzi DHCP. Consultare le istruzioni di ripristino e manutenzione.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
L'i/o del disco è molto lento
 a| 
L'i/o del disco molto lento potrebbe influire sulle prestazioni di StorageGRID.

. Se il problema riguarda un nodo dell'appliance di storage, utilizzare Gestione di sistema di SANtricity per verificare la presenza di dischi difettosi, dischi con guasti previsti o riparazioni dei dischi in corso. Controllare inoltre lo stato dei collegamenti Fibre Channel o SAS tra i controller di calcolo e storage dell'appliance per verificare se i collegamenti sono inattivi o mostrano tassi di errore eccessivi.
. Esaminare il sistema storage che ospita i volumi di questo nodo per determinare e correggere la causa principale del rallentamento dell'i/O.
. Se l'avviso persiste, contattare il supporto tecnico.



NOTE: I nodi interessati potrebbero disattivare i servizi e riavviarsi per evitare di influire sulle prestazioni complessive del grid. Quando la condizione sottostante viene cancellata e questi nodi rilevano le normali prestazioni i/o, tornano automaticamente al servizio completo.



 a| 
Errore di notifica e-mail
 a| 
Impossibile inviare la notifica email per un avviso.questo avviso viene attivato quando una notifica email di avviso non riesce o non può essere recapitata una email di test (inviata dalla pagina *Alerts* *Email Setup*).

. Accedere a Grid Manager dal nodo Admin elencato nella colonna *Sito/nodo* dell'avviso.
. Accedere alla pagina *Avvisi* *Configurazione e-mail*, controllare le impostazioni e modificarle se necessario.
. Fare clic su *Send Test Email* (Invia email di prova) e controllare la posta in arrivo di un destinatario del test. Se non è possibile inviare l'e-mail di prova, potrebbe essere attivata una nuova istanza di questo avviso.
. Se non è stato possibile inviare l'e-mail di prova, verificare che il server e-mail sia in linea.
. Se il server funziona, selezionare *Support* *Tools* *Logs* e raccogliere il log per il nodo di amministrazione. Specificare un periodo di tempo di 15 minuti prima e dopo l'ora dell'avviso.
. Estrarre l'archivio scaricato ed esaminare il contenuto di `prometheus.log` `(_/GID<gid><time_stamp>/<site_node>/<time_stamp>/metrics/prometheus.log)`.
. Se non si riesce a risolvere il problema, contattare il supporto tecnico.




 a| 
Scadenza dei certificati configurati nella pagina certificati client
 a| 
Uno o più certificati configurati nella pagina certificati client stanno per scadere.

. Selezionare *Configurazione* *controllo accessi* *certificati client*.
. Seleziona un certificato che scadrà a breve.
. Selezionare *Edit* (Modifica) per caricare o generare un nuovo certificato.
. Ripetere questa procedura per ogni certificato che scadrà a breve.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Scadenza del certificato endpoint del bilanciamento del carico
 a| 
Uno o più certificati endpoint per il bilanciamento del carico stanno per scadere.

. Selezionare *Configuration* > *Network Settings* > *Load Balancer Endpoints*.
. Selezionare un endpoint con un certificato che scadrà a breve.
. Selezionare *Edit endpoint* (Modifica endpoint) per caricare o generare un nuovo certificato.
. Ripetere questi passaggi per ogni endpoint con un certificato scaduto o che scadrà a breve.


Per ulteriori informazioni sulla gestione degli endpoint del bilanciamento del carico, vedere le istruzioni per l'amministrazione di StorageGRID.

link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Scadenza del certificato del server per l'interfaccia di gestione
 a| 
Il certificato del server utilizzato per l'interfaccia di gestione sta per scadere.

. Selezionare *Configurazione* *Impostazioni di rete* *certificati server*.
. Nella sezione Management Interface Server Certificate (certificato server interfaccia di gestione), caricare un nuovo certificato.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Scadenza del certificato del server per gli endpoint API dello storage
 a| 
Il certificato del server utilizzato per accedere agli endpoint API dello storage sta per scadere.

. Selezionare *Configurazione* *Impostazioni di rete* *certificati server*.
. Nella sezione Object Storage API Service Endpoints Server Certificate, caricare un nuovo certificato.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Mancata corrispondenza MTU rete griglia
 a| 
L'impostazione MTU (Maximum Transmission Unit) per l'interfaccia Grid Network (eth0) differisce significativamente tra i nodi della griglia.le differenze nelle impostazioni MTU potrebbero indicare che alcune reti eth0, ma non tutte, sono configurate per i frame jumbo. Una mancata corrispondenza delle dimensioni MTU superiore a 1000 potrebbe causare problemi di performance di rete.

link:../troubleshoot/troubleshooting-storagegrid-system.html["Risoluzione dei problemi relativi all'avviso di mancata corrispondenza MTU della rete griglia"]



 a| 
Elevato utilizzo di heap Java
 a| 
Viene utilizzata una percentuale elevata di spazio heap Java.se l'heap Java diventa pieno, i servizi di metadati possono non essere disponibili e le richieste del client potrebbero non riuscire.

. Esaminare l'attività ILM sulla dashboard. Questo avviso potrebbe essere risolto da solo quando il carico di lavoro ILM diminuisce.
. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Latenza elevata per le query sui metadati
 a| 
Il tempo medio per le query sui metadati Cassandra è troppo lungo. Un aumento della latenza delle query può essere causato da una modifica dell'hardware, come la sostituzione di un disco o una modifica del carico di lavoro, come un aumento improvviso delle attività di acquisizione.

. Determinare se sono state apportate modifiche all'hardware o al carico di lavoro nel tempo in cui la latenza della query è aumentata.
. Se non si riesce a risolvere il problema, contattare il supporto tecnico.




 a| 
Errore di sincronizzazione della federazione delle identità
 a| 
Impossibile sincronizzare utenti e gruppi federati dall'origine dell'identità.

. Verificare che il server LDAP configurato sia in linea e disponibile.
. Esaminare le impostazioni nella pagina Identity Federation (Federazione identità). Verificare che tutti i valori siano aggiornati. Consultare "`Configurazione di un'origine identità federata`" nelle istruzioni per l'amministrazione di StorageGRID.
. Fare clic su *Test Connection* (verifica connessione) per convalidare le impostazioni del server LDAP.
. Se non si riesce a risolvere il problema, contattare il supporto tecnico.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Posizionamento ILM non raggiungibile
 a| 
Non è possibile ottenere un'istruzione di posizionamento in una regola ILM per determinati oggetti.questo avviso indica che un nodo richiesto da un'istruzione di posizionamento non è disponibile o che una regola ILM è configurata in modo errato. Ad esempio, una regola potrebbe specificare un numero di copie replicate maggiore rispetto ai nodi di storage.

. Assicurarsi che tutti i nodi siano online.
. Se tutti i nodi sono in linea, rivedere le istruzioni di posizionamento in tutte le regole ILM che utilizzano il criterio ILM attivo. Verificare che siano presenti istruzioni valide per tutti gli oggetti. Consultare le istruzioni per la gestione degli oggetti con la gestione del ciclo di vita delle informazioni.
. Se necessario, aggiornare le impostazioni delle regole e attivare un nuovo criterio.
+

NOTE: L'eliminazione dell'avviso potrebbe richiedere fino a 1 giorno.

. Se il problema persiste, contattare il supporto tecnico.



NOTE: Questo avviso potrebbe essere visualizzato durante un aggiornamento e potrebbe persistere per 1 giorno dopo il completamento dell'aggiornamento. Quando questo avviso viene attivato da un aggiornamento, viene visualizzato da solo.

link:../ilm/index.html["Gestire gli oggetti con ILM"]



 a| 
Periodo di scansione ILM troppo lungo
 a| 
Il tempo necessario per eseguire la scansione, valutare gli oggetti e applicare ILM è troppo lungo.se il tempo stimato per completare una scansione ILM completa di tutti gli oggetti è troppo lungo (vedere *periodo di scansione - stimato* nella dashboard), il criterio ILM attivo potrebbe non essere applicato agli oggetti appena acquisiti. Le modifiche al criterio ILM potrebbero non essere applicate agli oggetti esistenti.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Verificare che tutti i nodi di storage siano online.
. Ridurre temporaneamente la quantità di traffico client. Ad esempio, da Grid Manager, selezionare *Configuration* *Network Settings* *Traffic Classification* e creare una policy che limiti la larghezza di banda o il numero di richieste.
. Se l'i/o del disco o la CPU sono sovraccarichi, provare a ridurre il carico o aumentare la risorsa.
. Se necessario, aggiornare le regole ILM per utilizzare il posizionamento sincrono (impostazione predefinita per le regole create dopo StorageGRID 11.3).
. Se l'avviso persiste, contattare il supporto tecnico.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Velocità di scansione ILM bassa
 a| 
La velocità di scansione ILM è impostata su un valore inferiore a 100 oggetti/secondo. Questo avviso indica che la velocità di scansione ILM del sistema è stata modificata a meno di 100 oggetti/secondo (impostazione predefinita: 400 oggetti/secondo). Il criterio ILM attivo potrebbe non essere applicato ai nuovi oggetti acquisiti. Le modifiche successive al criterio ILM non verranno applicate agli oggetti esistenti.

. Determinare se è stata apportata una modifica temporanea alla velocità di scansione ILM come parte di un'indagine di supporto in corso.
. Contattare il supporto tecnico.



IMPORTANT: Non modificare mai la velocità di scansione ILM senza contattare il supporto tecnico.



 a| 
Scadenza del certificato CA KMS
 a| 
Il certificato dell'autorità di certificazione (CA) utilizzato per firmare il certificato del server di gestione delle chiavi (KMS) sta per scadere.

. Utilizzando il software KMS, aggiornare il certificato CA per il server di gestione delle chiavi.
. Da Grid Manager, selezionare *Configuration* *System Settings* *Key Management Server*.
. Selezionare il KMS che presenta un avviso di stato del certificato.
. Selezionare *Modifica*.
. Selezionare *Avanti* per passare alla fase 2 (carica certificato server).
. Selezionare *Sfoglia* per caricare il nuovo certificato.
. Selezionare *Salva*.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Scadenza del certificato client KMS
 a| 
Il certificato client per un server di gestione delle chiavi sta per scadere.

. Da Grid Manager, selezionare *Configuration* *System Settings* *Key Management Server*.
. Selezionare il KMS che presenta un avviso di stato del certificato.
. Selezionare *Modifica*.
. Selezionare *Avanti* per passare alla fase 3 (carica certificati client).
. Selezionare *Sfoglia* per caricare il nuovo certificato.
. Selezionare *Sfoglia* per caricare la nuova chiave privata.
. Selezionare *Salva*.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Impossibile caricare la configurazione KMS
 a| 
La configurazione per il server di gestione delle chiavi esiste ma non è riuscita a caricarsi.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Errore di connettività KMS
 a| 
Un nodo appliance non è riuscito a connettersi al server di gestione delle chiavi del proprio sito.

. Da Grid Manager, selezionare *Configuration* *System Settings* *Key Management Server*.
. Verificare che le voci relative a porta e nome host siano corrette.
. Verificare che il certificato del server, il certificato del client e la chiave privata del certificato del client siano corretti e non scaduti.
. Assicurarsi che le impostazioni del firewall consentano al nodo dell'appliance di comunicare con il KMS specificato.
. Correggere eventuali problemi di rete o DNS.
. Se hai bisogno di assistenza o se l'avviso persiste, contatta il supporto tecnico.




 a| 
Nome chiave di crittografia KMS non trovato
 a| 
Il server di gestione delle chiavi configurato non dispone di una chiave di crittografia corrispondente al nome fornito.

. Verificare che il KMS assegnato al sito utilizzi il nome corretto per la chiave di crittografia e le versioni precedenti.
. Se hai bisogno di assistenza o se l'avviso persiste, contatta il supporto tecnico.




 a| 
Rotazione della chiave di crittografia KMS non riuscita
 a| 
Tutti i volumi dell'appliance sono stati decifrati, ma uno o più volumi non sono stati ruotati sulla chiave più recente.contattare il supporto tecnico.



 a| 
KMS non configurato
 a| 
Non esiste alcun server di gestione delle chiavi per questo sito.

. Da Grid Manager, selezionare *Configuration* *System Settings* *Key Management Server*.
. Aggiungere un KMS per questo sito o un KMS predefinito.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
La chiave KMS non è riuscita a decrittare un volume dell'appliance
 a| 
Non è stato possibile decifrare uno o più volumi su un'appliance con crittografia del nodo abilitata con la chiave KMS corrente.

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Assicurarsi che il server di gestione delle chiavi (KMS) disponga della chiave di crittografia configurata e di eventuali versioni precedenti.
. Se hai bisogno di assistenza o se l'avviso persiste, contatta il supporto tecnico.




 a| 
Scadenza del certificato del server KMS
 a| 
Il certificato del server utilizzato dal server di gestione delle chiavi (KMS) sta per scadere.

. Utilizzando il software KMS, aggiornare il certificato del server per il server di gestione delle chiavi.
. Se hai bisogno di assistenza o se l'avviso persiste, contatta il supporto tecnico.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Coda di audit di grandi dimensioni
 a| 
La coda dei dischi per i messaggi di controllo è piena.

. Controllare il carico sul sistema - se si è verificato un numero significativo di transazioni, l'avviso dovrebbe risolversi nel tempo e si può ignorare l'avviso.
. Se l'avviso persiste e aumenta di severità, visualizzare un grafico delle dimensioni della coda. Se il numero aumenta costantemente nel corso di ore o giorni, il carico di audit ha probabilmente superato la capacità di audit del sistema.
. Ridurre il tasso di operazioni del client o diminuire il numero di messaggi di controllo registrati modificando il livello di controllo per le scritture del client e le letture del client su Error (errore) o Off (*Configuration* *Monitoring* *Audit*).


link:../audit/index.html["Esaminare i registri di audit"]



 a| 
Bassa capacità del disco di log di audit
 a| 
Lo spazio disponibile per i registri di controllo è insufficiente.

. Monitorare questo avviso per verificare se il problema si risolve da solo e se lo spazio su disco diventa nuovamente disponibile.
. Contattare il supporto tecnico se lo spazio disponibile continua a diminuire.




 a| 
Memoria del nodo a bassa disponibilità
 a| 
La quantità di RAM disponibile su un nodo è bassa.una RAM disponibile bassa potrebbe indicare una modifica del carico di lavoro o una perdita di memoria con uno o più nodi.

. Monitorare questo avviso per verificare se il problema si risolve da solo.
. Se la memoria disponibile scende al di sotto della soglia di allarme principale, contattare il supporto tecnico.




 a| 
Spazio libero ridotto per il pool di storage
 a| 
La quantità di spazio disponibile per memorizzare i dati degli oggetti in un pool di storage è bassa.

. Selezionare *ILM* > *Storage Pools*.
. Selezionare il pool di storage elencato nell'avviso e selezionare *Visualizza dettagli*.
. Determinare dove è richiesta ulteriore capacità di storage. È possibile aggiungere nodi di storage a ciascun sito del pool di storage o aggiungere volumi di storage (LUN) a uno o più nodi di storage esistenti.
. Eseguire una procedura di espansione per aumentare la capacità dello storage.


link:../expand/index.html["Espandi il tuo grid"]



 a| 
Memoria del nodo installata insufficiente
 a| 
La quantità di memoria installata su un nodo è bassa.aumentare la quantità di RAM disponibile per la macchina virtuale o l'host Linux. Controllare il valore di soglia dell'avviso principale per determinare il requisito minimo predefinito per un nodo StorageGRID. Consultare le istruzioni per l'installazione della piattaforma:

* link:../rhel/index.html["Installare Red Hat Enterprise Linux o CentOS"]
* link:../ubuntu/index.html["Installare Ubuntu o Debian"]
* link:../vmware/index.html["Installare VMware"]




 a| 
Storage dei metadati basso
 a| 
Lo spazio disponibile per la memorizzazione dei metadati degli oggetti è basso.*Avviso critico*

. Interrompere l'acquisizione degli oggetti.
. Aggiungere immediatamente nodi di storage in una procedura di espansione.


*Allerta importante*

Aggiungere immediatamente nodi di storage in una procedura di espansione.

*Avviso minore*

. Monitorare la velocità di utilizzo dello spazio di metadati dell'oggetto. Selezionare *Nodes* *_Storage Node_* *Storage* e visualizzare il grafico Storage Used - Object Metadata.
. Aggiungere i nodi di storage in una procedura di espansione il prima possibile.


Una volta aggiunti nuovi nodi di storage, il sistema ribilancia automaticamente i metadati degli oggetti in tutti i nodi di storage e l'allarme viene cancellato.

link:../troubleshoot/troubleshooting-storagegrid-system.html["Risoluzione dei problemi relativi all'avviso di storage metadati in esaurimento"]

link:../expand/index.html["Espandi il tuo grid"]



 a| 
Capacità disco di metriche ridotte
 a| 
Lo spazio disponibile per il database delle metriche è basso.

. Monitorare questo avviso per verificare se il problema si risolve da solo e se lo spazio su disco diventa nuovamente disponibile.
. Contattare il supporto tecnico se lo spazio disponibile continua a diminuire.




 a| 
Storage dei dati a oggetti basso
 a| 
Lo spazio disponibile per la memorizzazione dei dati degli oggetti è insufficiente.eseguire una procedura di espansione. È possibile aggiungere volumi di storage (LUN) ai nodi di storage esistenti oppure aggiungere nuovi nodi di storage.

link:../troubleshoot/troubleshooting-storagegrid-system.html["Risoluzione dei problemi relativi all'avviso di storage dei dati a oggetti in esaurimento"]

link:../expand/index.html["Espandi il tuo grid"]



 a| 
Bassa capacità del disco root
 a| 
Lo spazio disponibile per il disco root è insufficiente.

. Monitorare questo avviso per verificare se il problema si risolve da solo e se lo spazio su disco diventa nuovamente disponibile.
. Contattare il supporto tecnico se lo spazio disponibile continua a diminuire.




 a| 
Bassa capacità dei dati di sistema
 a| 
Lo spazio disponibile per i dati del sistema StorageGRID nel file system /var/local è basso.

. Monitorare questo avviso per verificare se il problema si risolve da solo e se lo spazio su disco diventa nuovamente disponibile.
. Contattare il supporto tecnico se lo spazio disponibile continua a diminuire.




 a| 
Errore di connettività di rete del nodo
 a| 
Gli errori si sono verificati durante il trasferimento dei dati tra gli errori di connettività nodes.Network potrebbero essere chiari senza l'intervento manuale. Contattare il supporto tecnico se gli errori non sono chiari.

link:../troubleshoot/troubleshooting-storagegrid-system.html["Risoluzione dei problemi relativi all'allarme NRER (Network Receive Error)"]



 a| 
Errore frame ricezione rete nodo
 a| 
Un'elevata percentuale di frame di rete ricevuti da un nodo presentava errori. Questo avviso potrebbe indicare un problema hardware, ad esempio un cavo difettoso o un ricetrasmettitore guasto su entrambe le estremità della connessione Ethernet.

. Se si utilizza un'appliance, provare a sostituire ogni ricetrasmettitore e cavo SFP+ o SFP28, uno alla volta, per verificare se l'avviso scompare.
. Se l'avviso persiste, contattare il supporto tecnico.




 a| 
Nodo non sincronizzato con il server NTP
 a| 
L'ora del nodo non è sincronizzata con il server NTP (Network Time Protocol).

. Verificare di aver specificato almeno quattro server NTP esterni, ciascuno dei quali fornisce un riferimento di livello 3 o superiore.
. Verificare che tutti i server NTP funzionino correttamente.
. Verificare le connessioni ai server NTP. Assicurarsi che non siano bloccati da un firewall.




 a| 
Nodo non bloccato con server NTP
 a| 
Il nodo non è bloccato su un server NTP (Network Time Protocol).

. Verificare di aver specificato almeno quattro server NTP esterni, ciascuno dei quali fornisce un riferimento di livello 3 o superiore.
. Verificare che tutti i server NTP funzionino correttamente.
. Verificare le connessioni ai server NTP. Assicurarsi che non siano bloccati da un firewall.




 a| 
Rete nodo non appliance non in funzione
 a| 
Uno o più dispositivi di rete sono disconnessi o non attivi. Questo avviso indica che un'interfaccia di rete (eth) per un nodo installato su una macchina virtuale o su un host Linux non è accessibile.

Contattare il supporto tecnico.



 a| 
Oggetti persi
 a| 
Uno o più oggetti sono stati persi dalla griglia.questo avviso potrebbe indicare che i dati sono stati persi in modo permanente e non sono recuperabili.

. Esaminare immediatamente questo avviso. Potrebbe essere necessario intervenire per evitare ulteriori perdite di dati. Inoltre, se si esegue un'azione rapida, potrebbe essere possibile ripristinare un oggetto perso.
+
link:../troubleshoot/troubleshooting-storagegrid-system.html["Risoluzione dei problemi relativi ai dati degli oggetti persi e mancanti"]

. Una volta risolto il problema sottostante, azzerare il contatore:
+
.. Selezionare *supporto* > *Strumenti* > *topologia griglia*.
.. Per il nodo di storage che ha generato l'avviso, selezionare *_Site_* *_Grid Node_* *LDR* *Data Store* *Configuration* *Main*.
.. Selezionare *Reset Lost Objects Count* e fare clic su *Apply Changes* (Applica modifiche).






 a| 
Servizi della piattaforma non disponibili
 a| 
Pochi nodi di storage con il servizio RSM sono in esecuzione o disponibili in un sito.assicurarsi che la maggior parte dei nodi di storage che hanno il servizio RSM nel sito interessato sia in esecuzione e in uno stato non di errore.

Consultare "`risoluzione dei problemi relativi ai servizi della piattaforma`" nelle istruzioni per l'amministrazione di StorageGRID.

link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Collegamento dell'appliance di servizi alla porta di rete dell'amministratore 1
 a| 
La porta Admin Network 1 dell'appliance è inattiva o disconnessa.

. Controllare il cavo e la connessione fisica alla porta di rete amministrativa 1.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
Collegamento dell'appliance di servizi su Admin Network (o Client Network)
 a| 
L'interfaccia dell'appliance alla rete di amministrazione (eth1) o alla rete client (eth2) è inattiva o disconnessa.

. Controllare i cavi, gli SFP e le connessioni fisiche alla rete StorageGRID.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
Collegamento dell'appliance di servizi alla porta di rete 1, 2, 3 o 4
 a| 
La porta di rete 1, 2, 3 o 4 dell'appliance è inattiva o scollegata.

. Controllare i cavi, gli SFP e le connessioni fisiche alla rete StorageGRID.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
Connettività dello storage dell'appliance di servizi degradata
 a| 
Uno dei due SSD di un'appliance di servizi si è guastato o non è sincronizzato con l'altro. La funzionalità dell'appliance non è interessata, ma è necessario risolvere immediatamente il problema. Se entrambi i dischi si guastano, l'apparecchio non funzionerà più.

. Da Grid Manager, selezionare *Nodes* ***_Services appliance_, quindi selezionare la scheda **hardware*.
. Esaminare il messaggio nel campo *Storage RAID Mode* (modalità RAID storage).
. Se il messaggio indica lo stato di avanzamento di un'operazione di risincronizzazione, attendere il completamento dell'operazione, quindi confermare che l'avviso è stato risolto. Un messaggio di risincronizzazione indica che l'unità SSD è stata sostituita di recente o che viene risincronizzata per un altro motivo.
. Se il messaggio indica che uno degli SSD è guasto, sostituire il disco guasto non appena possibile.
+
Per istruzioni su come sostituire un disco in un'appliance di servizi, consultare la guida all'installazione e alla manutenzione delle appliance SG100 e SG1000.

+
link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]





 a| 
Collegamento dell'appliance di storage alla porta di rete dell'amministratore 1
 a| 
La porta Admin Network 1 dell'appliance è inattiva o disconnessa.

. Controllare il cavo e la connessione fisica alla porta di rete amministrativa 1.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
Collegamento dell'appliance di storage su Admin Network (o Client Network)
 a| 
L'interfaccia dell'appliance alla rete di amministrazione (eth1) o alla rete client (eth2) è inattiva o disconnessa.

. Controllare i cavi, gli SFP e le connessioni fisiche alla rete StorageGRID.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
Collegamento dell'appliance di storage alla porta di rete 1, 2, 3 o 4
 a| 
La porta di rete 1, 2, 3 o 4 dell'appliance è inattiva o scollegata.

. Controllare i cavi, gli SFP e le connessioni fisiche alla rete StorageGRID.
. Risolvere eventuali problemi di connessione. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
. Se questa porta viene disconnessa in base allo scopo, disattivare questa regola. In Grid Manager, selezionare *Alerts* *Alert Rules*, selezionare la regola e fare clic su *Edit rule* (Modifica regola). Quindi, deselezionare la casella di controllo *Enabled*.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]
** link:managing-alerts.html["Disattivazione di una regola di avviso"]






 a| 
La connettività dello storage dell'appliance di storage è degradata
 a| 
Si è verificato un problema con una o più connessioni tra il controller di calcolo e il controller dello storage.

. Controllare le spie degli indicatori di porta dall'apparecchio.
. Se le spie di una porta sono spente, verificare che il cavo sia collegato correttamente. Se necessario, sostituire il cavo.
. Attendere fino a cinque minuti.
+

NOTE: Se è necessario sostituire un secondo cavo, non scollegarlo per almeno 5 minuti. In caso contrario, il volume root potrebbe diventare di sola lettura, il che richiede un riavvio hardware.

. Da Grid Manager, selezionare *Nodes*. Quindi, selezionare la scheda hardware del nodo che ha riscontrato il problema. Verificare che la condizione di avviso sia stata risolta.




 a| 
Dispositivo di storage inaccessibile
 a| 
Impossibile accedere a un dispositivo di storage.questo avviso indica che non è possibile montare o accedere a un volume a causa di un problema con un dispositivo di storage sottostante.

. Controllare lo stato di tutti i dispositivi di storage utilizzati per il nodo:
+
** Se il nodo è installato su una macchina virtuale o su un host Linux, seguire le istruzioni del sistema operativo per eseguire la diagnostica hardware o eseguire un controllo del file system.
+
*** link:../rhel/index.html["Installare Red Hat Enterprise Linux o CentOS"]
*** link:../ubuntu/index.html["Installare Ubuntu o Debian"]
*** link:../vmware/index.html["Installare VMware"]


** Se il nodo è installato su un'appliance SG100, SG1000 o SG6000, utilizzare BMC.
** Se il nodo è installato su un'appliance SG5600 o SG5700, utilizzare Gestione di sistema di SANtricity.


. Se necessario, sostituire il componente. Consultare le istruzioni di installazione e manutenzione dell'hardware dell'appliance.
+
** link:../sg6000/index.html["Appliance di storage SG6000"]
** link:../sg5700/index.html["Appliance di storage SG5700"]
** link:../sg5600/index.html["Appliance di storage SG5600"]






 a| 
Utilizzo elevato della quota del tenant
 a| 
Viene utilizzata una percentuale elevata di spazio di quota tenant. Se un tenant supera la quota, i nuovi ingest vengono rifiutati.


NOTE: Questa regola di avviso è disattivata per impostazione predefinita perché potrebbe generare numerose notifiche.

. In Grid Manager, selezionare *tenant*.
. Ordinare la tabella in base a *quota Utilization*.
. Selezionare un tenant il cui utilizzo della quota è prossimo al 100%.
. Eseguire una o entrambe le operazioni seguenti:
+
** Selezionare *Edit* (Modifica) per aumentare la quota di storage per il tenant.
** Avvisare il tenant che l'utilizzo delle quote è elevato.






 a| 
Impossibile comunicare con il nodo
 a| 
Uno o più servizi non rispondono o il nodo non può essere raggiunto.questo avviso indica che un nodo è disconnesso per un motivo sconosciuto. Ad esempio, un servizio sul nodo potrebbe essere stato arrestato o il nodo potrebbe aver perso la connessione di rete a causa di un'interruzione dell'alimentazione o di un'interruzione imprevista.

Monitorare questo avviso per verificare se il problema si risolve da solo. Se il problema persiste:

. Determinare se è presente un altro avviso che interessa questo nodo. Questo avviso potrebbe essere risolto quando si risolve l'altro avviso.
. Verificare che tutti i servizi su questo nodo siano in esecuzione. Se un servizio viene arrestato, provare ad avviarlo. Consultare le istruzioni di ripristino e manutenzione.
. Assicurarsi che l'host del nodo sia acceso. In caso contrario, avviare l'host.
+

NOTE: Se più host sono spenti, consultare le istruzioni di ripristino e manutenzione.

. Determinare se si è verificato un problema di connettività di rete tra questo nodo e il nodo di amministrazione.
. Se non si riesce a risolvere l'avviso, contattare il supporto tecnico.


link:../maintain/index.html["Mantieni  Ripristina"]



 a| 
Riavvio del nodo imprevisto
 a| 
Un nodo si è riavviato inaspettatamente nelle ultime 24 ore.

. Monitorare questo avviso. L'avviso viene cancellato dopo 24 ore. Tuttavia, se il nodo si riavvia di nuovo inaspettatamente, questo avviso viene attivato di nuovo.
. Se non si riesce a risolvere l'avviso, potrebbe esserci un guasto hardware. Contattare il supporto tecnico.




 a| 
Rilevato oggetto corrotto non identificato
 a| 
È stato trovato un file nello storage a oggetti replicato che non è stato possibile identificare come oggetto replicato.

. Determinare se vi sono problemi con lo storage sottostante su un nodo di storage. Ad esempio, eseguire la diagnostica hardware o eseguire un controllo del file system.
. Dopo aver risolto eventuali problemi di storage, eseguire la verifica in primo piano per determinare se mancano oggetti e sostituirli, se possibile.
. Monitorare questo avviso. L'avviso verrà visualizzato dopo 24 ore, ma verrà nuovamente attivato se il problema non è stato risolto.
. Se non si riesce a risolvere l'avviso, contattare il supporto tecnico.


link:../troubleshoot/troubleshooting-storagegrid-system.html["Esecuzione della verifica in primo piano"]

|===
*Informazioni correlate*

link:commonly-used-prometheus-metrics.html["Metriche Prometheus comunemente utilizzate"]
