---
permalink: monitor/comparing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: alerts, alarms, comparing alerts and alarms 
summary: Esistono diverse analogie tra il sistema di allarme e il sistema di allarme legacy, ma il sistema di allarme offre notevoli vantaggi ed è più semplice da utilizzare. 
---
= Confronto di avvisi e allarmi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono diverse analogie tra il sistema di allarme e il sistema di allarme legacy, ma il sistema di allarme offre notevoli vantaggi ed è più semplice da utilizzare.

Fare riferimento alla seguente tabella per informazioni su come eseguire operazioni simili.

|===
|  | Avvisi | Allarmi (sistema precedente) 


 a| 
Come si visualizzano gli avvisi o gli allarmi attivi?
 a| 
* Fare clic sul collegamento *Current alerts* (Avvisi correnti) nella dashboard.
* Fare clic sull'avviso nella pagina *nodi* *Panoramica*.
* Selezionare *Avvisi* *corrente*.


link:viewing-current-alerts.html["Visualizzazione degli avvisi correnti"]
 a| 
* Fare clic sul collegamento *Legacy alarms* (Allarmi legacy) nella dashboard.
* Selezionare *supporto* *Allarmi (legacy)* *Allarmi correnti*.


link:viewing-legacy-alarms.html["Visualizzazione degli allarmi legacy"]



 a| 
Cosa causa l'attivazione di un avviso o di un avviso?
 a| 
Gli avvisi vengono attivati quando un'espressione Prometheus in una regola di avviso valuta true per la condizione di attivazione e la durata specifiche.

link:managing-alerts.html["Visualizzazione delle regole degli avvisi"]
 a| 
Gli allarmi vengono attivati quando un attributo StorageGRID raggiunge un valore di soglia.

link:managing-alarms.html["Logica di attivazione degli allarmi (sistema legacy)"]



 a| 
Se viene attivato un allarme o un allarme, come si risolve il problema sottostante?
 a| 
Le azioni consigliate per un avviso sono incluse nelle notifiche e-mail e sono disponibili nelle pagine Avvisi di Grid Manager.

Come richiesto, ulteriori informazioni sono fornite nella documentazione di StorageGRID.

link:alerts-reference.html["Riferimenti agli avvisi"]
 a| 
Per informazioni su un allarme, fare clic sul nome dell'attributo oppure cercare un codice di allarme nella documentazione di StorageGRID.

link:alarms-reference.html["Riferimento allarmi (sistema legacy)"]



 a| 
Dove è possibile visualizzare un elenco di avvisi o allarmi risolti?
 a| 
* Fare clic sul collegamento *Recently Resolved alerts* (Avvisi risolti di recente) nella dashboard
* Selezionare *Avvisi* *risolti*.


link:viewing-resolved-alerts.html["Visualizzazione degli avvisi risolti"]
 a| 
Selezionare *supporto* *Allarmi (legacy)* *Allarmi storici*.

link:managing-alarms.html["Revisione della cronologia degli allarmi e della frequenza degli allarmi (sistema precedente)"]



 a| 
Dove posso gestire le impostazioni?
 a| 
Selezionare *Avvisi*. Quindi, utilizzare le opzioni del menu Avvisi.

link:managing-alerts.html["Gestione degli avvisi"]
 a| 
Selezionare *supporto*. Quindi, utilizzare le opzioni nella sezione *Allarmi (legacy)* del menu.

link:managing-alarms.html["Gestione degli allarmi (sistema legacy)"]



 a| 
Quali autorizzazioni di gruppo utenti sono necessarie?
 a| 
* Chiunque possa accedere a Grid Manager può visualizzare gli avvisi correnti e risolti.
* È necessario disporre dell'autorizzazione Manage Alerts (Gestisci avvisi) per gestire silenzi, notifiche di avviso e regole di avviso.


link:../admin/index.html["Amministrare StorageGRID"]
 a| 
* Chiunque possa accedere a Grid Manager può visualizzare gli allarmi legacy.
* Per riconoscere gli allarmi, è necessario disporre dell'autorizzazione di riconoscimento degli allarmi.
* Per gestire gli allarmi globali e le notifiche e-mail, è necessario disporre delle autorizzazioni di configurazione della pagina topologia griglia e altre autorizzazioni di configurazione griglia.


link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Come si gestiscono le notifiche e-mail?
 a| 
Selezionare *Avvisi* *Configurazione e-mail*.

*Nota:* poiché gli allarmi e gli avvisi sono sistemi indipendenti, la configurazione dell'e-mail utilizzata per le notifiche di allarme e AutoSupport non viene utilizzata per le notifiche di avviso. Tuttavia, è possibile utilizzare lo stesso server di posta per tutte le notifiche.

link:managing-alerts.html["Gestione delle notifiche di avviso"]
 a| 
Selezionare *Support* *Alarms (legacy)* *Legacy Email Setup*. link:managing-alarms.html["Configurazione delle notifiche per gli allarmi (sistema legacy)"]



 a| 
Come si gestiscono le notifiche SNMP?
 a| 
Selezionare *Configuration* *Monitoring* *SNMP Agent*. link:using-snmp-monitoring.html["Utilizzo del monitoraggio SNMP"]
 a| 
Selezionare *Configuration* *Monitoring* *SNMP Agent*. link:using-snmp-monitoring.html["Utilizzo del monitoraggio SNMP"]

*Nota*: Le notifiche SNMP non vengono inviate per ogni allarme o gravità dell'allarme.

link:alarms-that-generate-snmp-notifications.html["Allarmi che generano notifiche SNMP (sistema legacy)"]



 a| 
Come posso controllare chi riceve le notifiche?
 a| 
. Selezionare *Avvisi* *Configurazione e-mail*.
. Nella sezione *destinatari*, immettere un indirizzo e-mail per ciascun elenco o persona che deve ricevere un'e-mail quando si verifica un avviso.


link:managing-alerts.html["Impostazione delle notifiche e-mail per gli avvisi"]
 a| 
. Selezionare *Support* *Alarms (legacy)* *Legacy Email Setup*.
. Creazione di una mailing list.
. Selezionare *Notifiche*.
. Selezionare la mailing list.


link:managing-alarms.html["Creazione di mailing list per le notifiche di allarme (sistema legacy)"]

link:managing-alarms.html["Configurazione delle notifiche e-mail per gli allarmi (sistema legacy)"]



 a| 
Quali nodi di amministrazione inviano notifiche?
 a| 
Un singolo nodo Admin (il "`Preferred sender`").

link:../admin/index.html["Amministrare StorageGRID"]
 a| 
Un singolo nodo Admin (il "`Preferred sender`").

link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Come posso eliminare alcune notifiche?
 a| 
. Selezionare *Avvisi* *silenzi*.
. Selezionare la regola di avviso che si desidera disattivare.
. Specificare la durata del silenzio.
. Selezionare il livello di gravità dell'avviso che si desidera disattivare.
. Selezionare per applicare il silenzio all'intera griglia, a un singolo sito o a un singolo nodo.


*Nota*: Se è stato attivato l'agente SNMP, le silenzi sopprimono anche i trap SNMP e informano.

link:managing-alerts.html["Tacitare le notifiche di avviso"]
 a| 
. Selezionare *Support* *Alarms (legacy)* *Legacy Email Setup*.
. Selezionare *Notifiche*.
. Selezionare una mailing list e selezionare *Sospendi*.


link:managing-alarms.html["Eliminazione delle notifiche di allarme per una mailing list (sistema legacy)"]



 a| 
Come posso eliminare tutte le notifiche?
 a| 
Selezionare *Alerts* *Silences*.quindi, selezionare *All rules*.

*Nota*: Se è stato attivato l'agente SNMP, le silenzi sopprimono anche i trap SNMP e informano.

link:managing-alerts.html["Tacitare le notifiche di avviso"]
 a| 
. Selezionare *Configurazione* > *Impostazioni di sistema* > *Opzioni di visualizzazione*.
. Selezionare la casella di controllo *notifica Sospendi tutto*.


*Nota*: La soppressione delle notifiche e-mail a livello di sistema elimina anche le e-mail AutoSupport attivate dagli eventi.

link:managing-alarms.html["Eliminazione delle notifiche e-mail a livello di sistema"]



 a| 
Come si personalizzano le condizioni e i trigger?
 a| 
. Selezionare *Avvisi* *regole avvisi*.
. Selezionare una regola predefinita da modificare oppure selezionare *Crea regola personalizzata*.


link:managing-alerts.html["Modifica di una regola di avviso"]

link:managing-alerts.html["Creazione di regole di avviso personalizzate"]
 a| 
. Selezionare *supporto* *Allarmi (legacy)* *Allarmi globali*.
. Creare un allarme personalizzato globale per ignorare un allarme predefinito o per monitorare un attributo che non ha un allarme predefinito.


link:managing-alarms.html["Creazione di allarmi personalizzati globali (sistema legacy)"]



 a| 
Come si disattiva un singolo avviso o allarme?
 a| 
. Selezionare *Avvisi* *regole avvisi*.
. Selezionare la regola e fare clic su *Modifica regola*.
. Deselezionare la casella di controllo *Enabled*.


link:managing-alerts.html["Disattivazione di una regola di avviso"]
 a| 
. Selezionare *supporto* *Allarmi (legacy)* *Allarmi globali*.
. Selezionare la regola e fare clic sull'icona Modifica.
. Deselezionare la casella di controllo *Enabled*.


link:managing-alarms.html["Disattivazione di un allarme predefinito (sistema legacy)"]

link:managing-alarms.html["Disattivazione degli allarmi Global Custom (sistema legacy)"]

|===