---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: I report di testo visualizzano una rappresentazione testuale dei valori dei dati degli attributi elaborati dal servizio NMS. È possibile creare report su un sito del data center, un nodo grid, un componente o un servizio. 
---
= Generazione di report di testo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I report di testo visualizzano una rappresentazione testuale dei valori dei dati degli attributi elaborati dal servizio NMS. È possibile creare report su un sito del data center, un nodo grid, un componente o un servizio.

.Di cosa hai bisogno
* È necessario accedere a Grid Manager utilizzando un browser supportato.
* È necessario disporre di autorizzazioni di accesso specifiche.


.A proposito di questa attività
Per i dati degli attributi che si prevede siano in continuo cambiamento, questi dati degli attributi vengono campionati dal servizio NMS (all'origine) a intervalli regolari. Per i dati degli attributi che cambiano di rado (ad esempio, dati basati su eventi come cambiamenti di stato o stato), un valore di attributo viene inviato al servizio NMS quando il valore cambia.

Il tipo di report visualizzato dipende dal periodo di tempo configurato. Per impostazione predefinita, i report di testo aggregati vengono generati per periodi di tempo superiori a una settimana.

Il testo grigio indica che il servizio è stato amministrativamente inattivo durante il campionamento. Il testo blu indica che il servizio si trova in uno stato sconosciuto.

.Fasi
. Selezionare *supporto* > *Strumenti* > *topologia griglia*.
. Selezionare *_grid node_* *_component o service_* *Report* *testo*.
. Selezionare l'attributo da segnalare dall'elenco a discesa *attributo*.
. Selezionare il numero di risultati per pagina dall'elenco a discesa *risultati per pagina*.
. Per arrotondare i valori a un massimo di tre cifre decimali (ad esempio, per gli attributi riportati come percentuali), deselezionare la casella di controllo *dati non elaborati*.
. Selezionare il periodo di tempo per il quale si desidera creare un report dall'elenco a discesa *Query rapida*.
+
Selezionare l'opzione Custom Query (Query personalizzata) per selezionare un intervallo di tempo specifico.

+
Il report viene visualizzato dopo alcuni istanti. Attendere alcuni minuti per la tabulazione di intervalli di tempo lunghi.

. Se si seleziona Custom Query (Query personalizzata), è necessario personalizzare il periodo di tempo per il quale si desidera creare un report inserendo *Data di inizio* e *Data di fine*.
+
Utilizzare il formato `YYYY/MM/DDHH:MM:SS` in ora locale. Gli zeri iniziali devono corrispondere al formato. Ad esempio, 2017/4/6 7:30:00 non supera la convalida. Il formato corretto è: 2017/04/06 07:30:00.

. Fare clic su *Aggiorna*.
+
Dopo alcuni istanti viene generato un report di testo. Attendere alcuni minuti per la tabulazione di intervalli di tempo lunghi. A seconda del periodo di tempo impostato per la query, viene visualizzato un report di testo raw o aggregato.

. Se si desidera stampare il report, fare clic con il pulsante destro del mouse e selezionare *Stampa*, quindi modificare le impostazioni della stampante necessarie e fare clic su *Stampa*.

