---
permalink: monitor/logs-for-third-party-software.html 
sidebar: sidebar 
keywords: troubleshooting, logs 
summary: È possibile utilizzare i registri del software di terze parti per risolvere i problemi. 
---
= Registri per software di terze parti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i registri del software di terze parti per risolvere i problemi.

|===
| Categoria | Nome del file | Note | Trovato in 


 a| 
log di apache2
 a| 
`/var/local/log/apache2/access.log /var/local/log/apache2/error.log`

`/var/local/log/apache2/other_vhosts_access.log`
 a| 
File di log per apache2.
 a| 
Nodi di amministrazione



 a| 
Archiviazione
 a| 
`/var/local/log/dsierror.log`
 a| 
Informazioni sugli errori per le API del client TSM.
 a| 
Nodi di archiviazione



 a| 
MySQL
 a| 
/var/local/log/mysql.err`

`/var/local/log/mysql.err /var/local/log/mysql-slow.log`
 a| 
File di log generati da MySQL.

Il file mysql.err acquisisce gli errori e gli eventi del database, ad esempio avvii e arresti.

Il file mysql-slow.log (log di query lento) acquisisce le istruzioni SQL che hanno richiesto più di 10 secondi per l'esecuzione.
 a| 
Nodi di amministrazione



 a| 
Sistema operativo
 a| 
`/var/local/log/messages`
 a| 
Questa directory contiene i file di log per il sistema operativo. Gli errori contenuti in questi log vengono visualizzati anche in Grid Manager. Selezionare *supporto* *Strumenti* *topologia griglia*. Quindi selezionare *topologia* *_Sito_* *_nodo_* *SSM* *Eventi*.
 a| 
Tutti i nodi



 a| 
NTP
 a| 
`/var/local/log/ntp.log`

`/var/lib/ntp/var/log/ntpstats/`
 a| 
Il `/var/local/log/ntp.log` Contiene il file di log per i messaggi di errore NTP.

Il `/var/lib/ntp/var/log/ntpstats/` La directory contiene le statistiche di tempo NTP.

`loopstats` registra le informazioni statistiche del filtro loop.

`peerstats` registra le informazioni delle statistiche peer.
 a| 
Tutti i nodi



 a| 
Samba
 a| 
`/var/local/log/samba/`
 a| 
La directory di log di Samba include un file di log per ogni processo Samba (smb, nmb e winbind) e per ogni nome host/IP del client.
 a| 
Nodo di amministrazione configurato per esportare la condivisione di controllo su CIFS

|===