---
permalink: maintain/recovering-from-non-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, non-primary admin node failure 
summary: 'È necessario completare le seguenti attività per eseguire il ripristino da un errore non primario del nodo di amministrazione. Un nodo di amministrazione ospita il servizio CMN (Configuration Management Node) ed è noto come nodo di amministrazione primario. Sebbene sia possibile avere più nodi di amministrazione, ogni sistema StorageGRID include un solo nodo di amministrazione primario. Tutti gli altri nodi Admin non sono nodi Admin primari.' 
---
= Ripristino da errori non primari del nodo di amministrazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario completare le seguenti attività per eseguire il ripristino da un errore non primario del nodo di amministrazione. Un nodo amministratore ospita il servizio CMN (Configuration Management Node) ed è noto come nodo amministratore primario. Sebbene sia possibile avere più nodi di amministrazione, ogni sistema StorageGRID include un solo nodo di amministrazione primario. Tutti gli altri nodi Admin non sono nodi Admin primari.

.Informazioni correlate
link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]

.Fasi
* link:copying-audit-logs-from-failed-non-primary-admin-node.html["Copia dei registri di controllo dal nodo di amministrazione non primario non riuscito"]
* link:replacing-non-primary-admin-node.html["Sostituzione di un nodo amministrativo non primario"]
* link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Selezionare Start Recovery (Avvia ripristino) per configurare un nodo di amministrazione non primario"]
* link:restoring-audit-log-on-recovered-non-primary-admin-node.html["Ripristino del registro di controllo sul nodo Admin non primario recuperato"]
* link:resetting-preferred-sender-on-recovered-non-primary-admin-node.html["Reimpostazione del mittente preferito sul nodo di amministrazione non primario recuperato"]
* link:restoring-admin-node-database-non-primary-admin-node.html["Ripristino del database Admin Node durante il ripristino di un nodo Admin non primario"]
* link:restoring-prometheus-metrics-non-primary-admin-node.html["Ripristino delle metriche Prometheus durante il ripristino di un nodo di amministrazione non primario"]

