---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: È possibile chiudere un nodo Grid dalla shell dei comandi del nodo. 
---
= Chiusura di un nodo di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile chiudere un nodo Grid dalla shell dei comandi del nodo.

.Di cosa hai bisogno
* È necessario disporre di `Passwords.txt` file.


.A proposito di questa attività
Prima di eseguire questa procedura, esaminare le seguenti considerazioni:

* In generale, non è necessario spegnere più di un nodo alla volta per evitare interruzioni.
* Non spegnere un nodo durante una procedura di manutenzione, a meno che non venga espressamente richiesto dalla documentazione o dal supporto tecnico.
* Il processo di shutdown si basa sulla posizione in cui è installato il nodo, come segue:
+
** L'arresto di un nodo VMware arresta la macchina virtuale.
** L'arresto di un nodo Linux arresta il container.
** L'arresto di un nodo appliance StorageGRID arresta il controller di calcolo.


* Se si prevede di arrestare i nodi di storage, tenere presente quanto segue:
+
** Se una regola ILM specifica un comportamento di acquisizione di doppio commit o la regola specifica Balanced (bilanciato) e non è possibile creare immediatamente tutte le copie richieste, StorageGRID commuta immediatamente tutti gli oggetti acquisiti di recente su due nodi di storage sullo stesso sito e valuta ILM in un secondo momento. Se si desidera arrestare due o più nodi di storage in un determinato sito, potrebbe non essere possibile accedere a questi oggetti per la durata della chiusura.
** Per garantire l'accesso a tutti gli oggetti quando un nodo di storage viene spento, interrompere l'acquisizione di oggetti in un sito per circa un'ora prima di spegnere il nodo.




.Fasi
. Accedere al nodo Grid:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.

. Arrestare tutti i servizi: `service servermanager stop`
+
L'arresto dei servizi può richiedere fino a 15 minuti e potrebbe essere necessario accedere al sistema in remoto per monitorare il processo di arresto.

. Disconnettersi dalla shell dei comandi: `exit`


Dopo essere stato spento, è possibile spegnere il nodo della rete.

link:powering-down-host.html["Spegnere un host"]

.Informazioni correlate
link:../admin/index.html["Amministrare StorageGRID"]
