---
permalink: maintain/stopping-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop server manager, stop all services, stop services 
summary: Server Manager è progettato per essere eseguito in qualsiasi momento, ma potrebbe essere necessario interrompere Server Manager e tutti i servizi in esecuzione su un nodo grid. 
---
= Interruzione di Server Manager e di tutti i servizi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Manager è progettato per essere eseguito in qualsiasi momento, ma potrebbe essere necessario interrompere Server Manager e tutti i servizi in esecuzione su un nodo grid.

.Di cosa hai bisogno
È necessario disporre di `Passwords.txt` file.

.A proposito di questa attività
L'unico scenario che richiede l'arresto di Server Manager mantenendo il sistema operativo in esecuzione è quando è necessario integrare Server Manager ad altri servizi. Se è necessario arrestare Server Manager per la manutenzione dell'hardware o per la riconfigurazione del server, arrestare l'intero server.

.Fasi
. Accedere al nodo Grid:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.

. Arrestare Server Manager e tutti i servizi in esecuzione sul nodo grid: `service servermanager stop`
+
Server Manager e tutti i servizi in esecuzione sul nodo grid vengono terminati senza problemi. L'arresto dei servizi può richiedere fino a 15 minuti.

. Disconnettersi dalla shell dei comandi: `exit`

