---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, shut down nodes, node shutdown 
summary: Prima di spegnere un sistema StorageGRID, è necessario arrestare tutti i servizi in esecuzione su ciascun nodo di rete e quindi arrestare tutte le macchine virtuali VMware, i container Docker e le appliance StorageGRID. 
---
= Interruzione dei servizi e chiusura dei nodi di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di spegnere un sistema StorageGRID, è necessario arrestare tutti i servizi in esecuzione su ciascun nodo di rete e quindi arrestare tutte le macchine virtuali VMware, i container Docker e le appliance StorageGRID.

.A proposito di questa attività
Se possibile, interrompere i servizi sui nodi della griglia in questo ordine:

* Interrompere prima i servizi sui nodi gateway.
* Interrompere per ultimi i servizi sul nodo di amministrazione primario.


Questo approccio consente di utilizzare l'Admin Node primario per monitorare lo stato degli altri nodi della griglia il più a lungo possibile.


NOTE: Se un singolo host include più di un nodo di griglia, non spegnere l'host fino a quando non sono stati arrestati tutti i nodi su tale host. Se l'host include il nodo di amministrazione primario, arrestare l'host per ultimo.


NOTE: Se necessario, è possibile migrare i nodi da un host Linux a un altro per eseguire la manutenzione degli host senza influire sulle funzionalità o sulla disponibilità del grid.

link:linux-migrating-grid-node-to-new-host.html["Linux: Migrazione di un nodo grid a un nuovo host"]

.Fasi
. Impedire a tutte le applicazioni client di accedere alla griglia.
. [[log_in_to_gn]]Accedi a ciascun nodo gateway:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



. [[stop_all_Services]]Arresta tutti i servizi in esecuzione sul nodo: `service servermanager stop`
+
L'arresto dei servizi può richiedere fino a 15 minuti e potrebbe essere necessario accedere al sistema in remoto per monitorare il processo di arresto.



. Ripetere i due passaggi precedenti per arrestare i servizi su tutti i nodi di storage, i nodi di archivio e i nodi di amministrazione non primari.
+
È possibile interrompere i servizi su questi nodi in qualsiasi ordine.

+

NOTE: Se si esegue il `service servermanager stop` Per arrestare i servizi su un nodo di storage dell'appliance, è necessario spegnere e riaccendere l'appliance per riavviare il nodo.

. Per il nodo di amministrazione principale, ripetere i passaggi per <<log_in_to_gn,accesso al nodo>> e. <<stop_all_services,interruzione di tutti i servizi sul nodo>>.
. Per i nodi in esecuzione su host Linux:
+
.. Accedere al sistema operativo host.
.. Arrestare il nodo: `storagegrid node stop`
.. Arrestare il sistema operativo host.


. Per i nodi in esecuzione sulle macchine virtuali VMware e per i nodi di storage dell'appliance, eseguire il comando shutdown: `shutdown -h now`
+
Eseguire questa operazione indipendentemente dal risultato dell' `service servermanager stop` comando.

+
Per l'appliance, questo comando arresta il controller di calcolo, ma l'appliance è ancora accesa. Completare la fase successiva.

. Se si dispone di nodi appliance:
+
** Per l'appliance di servizi SG100 o SG1000
+
... Spegnere l'apparecchio.
... Attendere che il LED di alimentazione blu si spenga.


** Per l'appliance SG6000
+
... Attendere che il LED verde cache Active (cache attiva) sul retro del controller dello storage si spenga.
+
Questo LED si accende quando i dati memorizzati nella cache devono essere scritti sui dischi. Prima di spegnere il prodotto, attendere che il LED si spenga.

... Spegnere l'apparecchio e attendere che il LED di alimentazione blu si spenga.


** Per l'appliance SG5700
+
... Attendere che il LED verde cache Active (cache attiva) sul retro del controller dello storage si spenga.
+
Questo LED si accende quando i dati memorizzati nella cache devono essere scritti sui dischi. Prima di spegnere il prodotto, attendere che il LED si spenga.

... Spegnere l'apparecchio e attendere che il LED e il display a sette segmenti si interrompano.




. Se necessario, disconnettersi dalla shell dei comandi: `exit`
+
La griglia StorageGRID è stata chiusa.



.Informazioni correlate
link:../sg100-1000/index.html["SG100  SG1000 Services appliance"]

link:../sg6000/index.html["Appliance di storage SG6000"]

link:../sg5700/index.html["Appliance di storage SG5700"]
