---
permalink: primer/tabs-for-nodes-page.html 
sidebar: sidebar 
keywords: nodes page, hardware tab, network tab, storage tab, events tab, objects tab, ilm tab, load balancer tab, platform services tab, santricity system manager tab 
summary: Le schede nella parte superiore della pagina nodi si basano su ciò che si seleziona dalla struttura a sinistra. 
---
= Schede per la pagina nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le schede nella parte superiore della pagina nodi si basano su ciò che si seleziona dalla struttura a sinistra.

[cols="1a,2a,1a"]
|===
| Nome scheda | Descrizione | Incluso per 


 a| 
Panoramica
 a| 
* Fornisce informazioni di base su ciascun nodo.
* Mostra gli allarmi correnti non riconosciuti che interessano il nodo.

 a| 
Tutti i nodi



 a| 
Hardware
 a| 
* Visualizza l'utilizzo della CPU e della memoria per ciascun nodo
* Per i nodi appliance, fornisce informazioni aggiuntive sull'hardware.

 a| 
Tutti i nodi



 a| 
Rete
 a| 
Visualizza un grafico che mostra il traffico di rete ricevuto e inviato attraverso le interfacce di rete.
 a| 
Tutti i nodi, ciascun sito e l'intero grid



 a| 
Storage
 a| 
* Fornisce informazioni dettagliate sui dischi e sui volumi su ciascun nodo.
* Per i nodi di storage, ogni sito e l'intero grid include grafici che mostrano lo storage dei dati a oggetti e lo storage dei metadati utilizzati nel tempo.

 a| 
Tutti i nodi, ciascun sito e l'intero grid



 a| 
Eventi
 a| 
Visualizza il numero di errori di sistema o di errori, inclusi errori come gli errori di rete.
 a| 
Tutti i nodi



 a| 
Oggetti
 a| 
* Fornisce informazioni sulle velocità di acquisizione e recupero di S3 e Swift.
* Per i nodi di storage, fornisce conteggi di oggetti e informazioni sulle query dell'archivio di metadati e sulla verifica in background.

 a| 
Nodi di storage, ciascun sito e l'intero grid



 a| 
ILM
 a| 
Fornisce informazioni sulle operazioni ILM (Information Lifecycle Management).

* Per i nodi di storage, fornisce dettagli sulla valutazione ILM e sulla verifica in background per l'eliminazione degli oggetti codificati.
* Per ogni sito e per l'intera griglia, mostra un grafico della coda ILM nel tempo.
* Per l'intera griglia, fornisce il tempo stimato per completare una scansione ILM completa di tutti gli oggetti.

 a| 
Nodi di storage, ciascun sito e l'intero grid



 a| 
Bilanciamento del carico
 a| 
Include grafici diagnostici e relativi alle performance del servizio Load Balancer.

* Per ogni sito, fornisce un riepilogo aggregato delle statistiche per tutti i nodi del sito.
* Per l'intero grid, fornisce un riepilogo aggregato delle statistiche per tutti i siti.

 a| 
Nodi di amministrazione e nodi gateway, ciascun sito e l'intero grid



 a| 
Platform Services (servizi piattaforma)
 a| 
Fornisce informazioni sulle operazioni di servizio della piattaforma S3 in un sito.
 a| 
Ogni sito



 a| 
Gestore di sistema di SANtricity
 a| 
Fornisce l'accesso a Gestione di sistema di SANtricity. Da Gestore di sistema di SANtricity, è possibile esaminare le informazioni ambientali e di diagnostica hardware per il controller di storage, nonché i problemi relativi ai dischi.
 a| 
Nodi di appliance di storage

*Nota:* la scheda Gestore di sistema di SANtricity non viene visualizzata se il firmware del controller sul dispositivo di storage è inferiore a 8.70.

|===