---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, node, site, add, adding, expand, expansion 
summary: È possibile seguire questa procedura per aggiungere nodi di griglia a siti esistenti o per aggiungere un nuovo sito, ma non è possibile eseguire entrambi i tipi di espansione contemporaneamente. 
---
= Aggiunta di nodi di griglia a un sito esistente o aggiunta di un nuovo sito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile seguire questa procedura per aggiungere nodi di griglia a siti esistenti o per aggiungere un nuovo sito, ma non è possibile eseguire entrambi i tipi di espansione contemporaneamente.

.Di cosa hai bisogno
* È necessario disporre dei permessi root o di manutenzione. Per ulteriori informazioni, vedere la sezione relativa al controllo dell'accesso al sistema con account utente e gruppi di amministrazione.
* Tutti i nodi esistenti nella griglia devono essere attivi e funzionanti in tutti i siti.
* Tutte le precedenti procedure di espansione, aggiornamento, disattivazione o ripristino devono essere completate.
+

NOTE: Non è possibile avviare un'espansione mentre è in corso un'altra procedura di espansione, aggiornamento, ripristino o decommissionamento attivo. Tuttavia, se necessario, è possibile sospendere una procedura di decommissionamento per avviare un'espansione.



.Fasi
. link:updating-subnets-for-grid-network.html["Aggiornamento delle subnet per la rete Grid"]
. link:deploying-new-grid-nodes.html["Implementazione di nuovi nodi grid"]
. link:performing-expansion.html["Esecuzione dell'espansione"]

