---
permalink: expand/configuring-expanded-storagegrid-system.html 
sidebar: sidebar 
keywords: expansion, configuration 
summary: 'Dopo aver completato un"espansione, è necessario eseguire ulteriori operazioni di integrazione e configurazione.' 
---
= Configurazione del sistema Expanded StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato un'espansione, è necessario eseguire ulteriori operazioni di integrazione e configurazione.

.A proposito di questa attività
È necessario completare le attività di configurazione elencate di seguito per i nodi griglia che si stanno aggiungendo all'espansione. Alcune attività potrebbero essere facoltative, a seconda delle opzioni selezionate durante l'installazione e l'amministrazione del sistema e di come si desidera configurare i nodi della griglia aggiunti durante l'espansione.

.Fasi
. Se è stato aggiunto un nodo di storage, completare le seguenti attività di configurazione.
+
[cols="2a,1a"]
|===
| Attività di configurazione del nodo di storage | Per informazioni 


 a| 
Esaminare i pool di storage utilizzati nelle regole ILM per assicurarsi che venga utilizzato il nuovo storage.

** Se è stato aggiunto un sito, creare un pool di storage per il sito e aggiornare le regole ILM per utilizzare il nuovo pool di storage.
** Se è stato aggiunto un nodo di storage a un sito esistente, verificare che il nuovo nodo utilizzi il livello di storage corretto.
+
*Nota:* per impostazione predefinita, un nuovo nodo di storage viene assegnato al livello di storage All Storage Node e aggiunto ai pool di storage che utilizzano tale livello per il sito. Se si desidera che un nuovo nodo utilizzi un livello di storage personalizzato, è necessario assegnarlo manualmente al livello di storage personalizzato (*ILM* > *Storage Grades*).


 a| 
link:../ilm/index.html["Gestire gli oggetti con ILM"]



 a| 
Verificare che il nodo di storage stia acquisendo oggetti.
 a| 
link:verifying-storage-node-is-active.html["Verificare che il nodo di storage sia attivo"]



 a| 
Ribilanciare i dati con codifica di cancellazione (solo se non è stato possibile aggiungere il numero consigliato di nodi di storage).
 a| 
link:rebalancing-erasure-coded-data-after-adding-storage-nodes.html["Ribilanciamento dei dati con codifica erasure dopo l'aggiunta di nodi di storage"]

|===
. Se è stato aggiunto un nodo gateway, completare le seguenti attività di configurazione.
+
[cols="2a,1a"]
|===
| Attività di configurazione del nodo gateway | Per informazioni 


 a| 
Se i gruppi ad alta disponibilità vengono utilizzati per le connessioni client, aggiungere i nodi gateway a un gruppo ha. Selezionare *Configuration* > *Network Settings* > *High Availability Groups* (Configurazione* > *Impostazioni di rete*) per esaminare l'elenco dei gruppi ha esistenti e aggiungere i nuovi nodi.
 a| 
link:../admin/index.html["Amministrare StorageGRID"]

|===
. Se è stato aggiunto un nodo di amministrazione, completare le seguenti attività di configurazione.
+
[cols="2a,1a"]
|===
| Attività di configurazione del nodo di amministrazione | Per informazioni 


 a| 
Se il single sign-on è attivato per il sistema StorageGRID, è necessario creare un trust per la parte che si basa nei servizi di federazione di Active Directory (ad FS) per il nuovo nodo amministratore. Non è possibile accedere al nodo fino a quando non si crea questo trust per la parte di base.
 a| 
link:../admin/configuring-sso.html["Configurazione del single sign-on"]



 a| 
Se si intende utilizzare il servizio Load Balancer sui nodi Admin, potrebbe essere necessario aggiungere i nodi Admin ai gruppi ad alta disponibilità. Selezionare *Configuration* > *Network Settings* > *High Availability Groups* (Configurazione* > *Impostazioni di rete*) per esaminare l'elenco dei gruppi ha esistenti e aggiungere i nuovi nodi.
 a| 
link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Facoltativamente, copiare il database del nodo di amministrazione dal nodo di amministrazione primario al nodo di amministrazione di espansione se si desidera mantenere costanti le informazioni di attributo e controllo su ciascun nodo di amministrazione.
 a| 
link:copying-admin-node-database.html["Copia del database Admin Node"]



 a| 
Facoltativamente, copiare il database Prometheus dal nodo di amministrazione primario al nodo di amministrazione di espansione se si desidera mantenere costanti le metriche storiche su ciascun nodo di amministrazione.
 a| 
link:copying-prometheus-metrics.html["Copia delle metriche Prometheus"]



 a| 
Facoltativamente, copiare i registri di controllo esistenti dal nodo di amministrazione principale al nodo di amministrazione dell'espansione se si desidera mantenere coerenti le informazioni di registro cronologiche su ciascun nodo di amministrazione.
 a| 
link:copying-audit-logs.html["Copia dei registri di audit"]



 a| 
Facoltativamente, configurare l'accesso al sistema per scopi di controllo tramite una condivisione file NFS o CIFS.

*Nota:* l'esportazione dell'audit tramite CIFS/Samba è stata deprecata e verrà rimossa in una futura release di StorageGRID.
 a| 
link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Facoltativamente, modificare il mittente preferito per le notifiche. È possibile impostare l'Admin Node di espansione come mittente preferito. In caso contrario, un nodo amministrativo esistente configurato come mittente preferito continua a inviare notifiche, tra cui messaggi AutoSupport, notifiche SNMP, e-mail di avviso ed e-mail di allarme (sistema legacy).
 a| 
link:../admin/index.html["Amministrare StorageGRID"]

|===
. Se è stato aggiunto un nodo di archiviazione, completare le seguenti attività di configurazione.
+
[cols="2a,1a"]
|===
| Attività di configurazione del nodo di archiviazione | Per informazioni 


 a| 
Configurare la connessione del nodo di archiviazione al sistema di archiviazione esterno di destinazione. Una volta completata l'espansione, i nodi di archiviazione si trovano in uno stato di allarme fino a quando non si configurano le informazioni di connessione tramite il componente *ARC* > *Target*.
 a| 
link:../admin/index.html["Amministrare StorageGRID"]



 a| 
Aggiornare il criterio ILM per archiviare i dati dell'oggetto attraverso il nuovo nodo di archivio.
 a| 
link:../ilm/index.html["Gestire gli oggetti con ILM"]



 a| 
Configurare gli allarmi personalizzati per gli attributi utilizzati per monitorare la velocità e l'efficienza del recupero dei dati degli oggetti dai nodi di archiviazione.
 a| 
link:../admin/index.html["Amministrare StorageGRID"]

|===
. Per verificare se i nodi di espansione sono stati aggiunti con una rete client non attendibile o per modificare se la rete client di un nodo è non attendibile o attendibile, andare a *Configurazione* > *Impostazioni di rete* > *rete client non attendibile*.
+
Se la rete client sul nodo di espansione non è attendibile, le connessioni al nodo sulla rete client devono essere effettuate utilizzando un endpoint di bilanciamento del carico. Per ulteriori informazioni, consultare le istruzioni per l'amministrazione di StorageGRID.

. Configurare il DNS (Domain Name System).
+
Se le impostazioni DNS sono state specificate separatamente per ciascun nodo della griglia, è necessario aggiungere impostazioni DNS personalizzate per nodo per i nuovi nodi. Consultare le informazioni sulla modifica della configurazione DNS per un singolo nodo della griglia nelle istruzioni di ripristino e manutenzione.

+
La procedura consigliata prevede che l'elenco dei server DNS a livello di griglia contenga alcuni server DNS accessibili localmente da ciascun sito. Se è stato appena aggiunto un nuovo sito, aggiungere nuovi server DNS per il sito alla configurazione DNS a livello di griglia.

+

IMPORTANT: Fornire da due a sei indirizzi IPv4 per i server DNS. Selezionare i server DNS ai quali ciascun sito può accedere localmente in caso di rete. In questo modo si garantisce che un sito islanded continui ad avere accesso al servizio DNS. Dopo aver configurato l'elenco dei server DNS a livello di griglia, è possibile personalizzare ulteriormente l'elenco dei server DNS per ciascun nodo. Per ulteriori informazioni, vedere le informazioni sulla modifica della configurazione DNS nelle istruzioni di ripristino e manutenzione.

. Se è stato aggiunto un nuovo sito, verificare che i server NTP (Network Time Protocol) siano accessibili da tale sito.
+

IMPORTANT: Assicurarsi che almeno due nodi di ciascun sito possano accedere ad almeno quattro origini NTP esterne. Se solo un nodo di un sito può raggiungere le origini NTP, si verificheranno problemi di tempistica se tale nodo non funziona. Inoltre, la designazione di due nodi per sito come origini NTP primarie garantisce tempi precisi se un sito viene isolato dal resto della rete.

+
Per ulteriori informazioni, consultare le istruzioni di ripristino e manutenzione.



.Informazioni correlate
link:../ilm/index.html["Gestire gli oggetti con ILM"]

link:verifying-storage-node-is-active.html["Verificare che il nodo di storage sia attivo"]

link:copying-admin-node-database.html["Copia del database Admin Node"]

link:copying-prometheus-metrics.html["Copia delle metriche Prometheus"]

link:copying-audit-logs.html["Copia dei registri di audit"]

link:../upgrade/index.html["Aggiornare il software"]

link:../maintain/index.html["Mantieni  Ripristina"]
