---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 'Quando si aggiunge un nuovo nodo amministratore mediante una procedura di espansione, il servizio AMS registra solo gli eventi e le azioni che si verificano dopo l"accesso al sistema. È possibile copiare i registri di controllo da un nodo di amministrazione precedentemente installato al nuovo nodo di amministrazione di espansione in modo che sia sincronizzato con il resto del sistema StorageGRID.' 
---
= Copia dei registri di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiunge un nuovo nodo amministratore mediante una procedura di espansione, il servizio AMS registra solo gli eventi e le azioni che si verificano dopo l'accesso al sistema. È possibile copiare i registri di controllo da un nodo di amministrazione precedentemente installato al nuovo nodo di amministrazione di espansione in modo che sia sincronizzato con il resto del sistema StorageGRID.

.Di cosa hai bisogno
* Per aggiungere un nodo di amministrazione, è necessario aver completato le fasi di espansione richieste.
* È necessario disporre di `Passwords.txt` file.


.A proposito di questa attività
Per rendere disponibili i messaggi di audit storici da altri nodi di amministrazione sul nodo di amministrazione dell'espansione, è necessario copiare manualmente i file di log dell'audit dal nodo di amministrazione primario o da un altro nodo di amministrazione esistente al nodo di amministrazione dell'espansione.

.Fasi
. Accedere al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



. Arrestare il servizio AMS per impedire la creazione di un nuovo file: `service ams stop`
. Rinominare il `audit.log` File per assicurarsi che non sovrascriva il file sul nodo di amministrazione dell'espansione in cui si sta copiando:
+
`cd /var/local/audit/export` +
`ls -l` +
`mv audit.log _new_name_.txt`

. Copiare tutti i file di log dell'audit nel nodo di amministrazione dell'espansione:
+
`scp -p * _IP_address_:/var/local/audit/export`

. Se viene richiesta la passphrase per `/root/.ssh/id_rsa`, Immettere la password di accesso SSH per il nodo di amministrazione principale elencato in `Passwords.txt` file.
. Ripristinare l'originale `audit.log` file:
+
`mv _new_name_.txt audit.log`

. Avviare il servizio AMS:
+
`service ams start`

. Disconnettersi dal server:
+
`exit`

. Accedere al nodo di amministrazione dell'espansione:
+
.. Immettere il seguente comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



. Aggiornare le impostazioni dell'utente e del gruppo per i file di log di controllo:
+
`cd /var/local/audit/export` +
`chown ams-user:bycast *`

. Disconnettersi dal server:
+
`exit`


