---
permalink: troubleshoot/troubleshooting-delivery-platform-services-messages.html 
sidebar: sidebar 
keywords:  
summary: 'L"allarme SMTT (Total Events) viene attivato in Grid Manager se un messaggio di servizio della piattaforma viene inviato a una destinazione che non può accettare i dati.' 
---
= Troubleshooting delivery of platform Services messages (allarme SMTT)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'allarme SMTT (Total Events) viene attivato in Grid Manager se un messaggio di servizio della piattaforma viene inviato a una destinazione che non può accettare i dati.

.A proposito di questa attività
Ad esempio, un caricamento di S3 multiparte può avere successo anche se la replica o il messaggio di notifica associati non possono essere inviati all'endpoint configurato. In alternativa, un messaggio per la replica di CloudMirror potrebbe non essere recapitato se i metadati sono troppo lunghi.

L'allarme SMTT contiene un messaggio Last Event (ultimo evento) che indica: `Failed to publish notifications for _bucket-name object key_` per l'ultimo oggetto la cui notifica non è riuscita.

Per ulteriori informazioni sulla risoluzione dei problemi relativi ai servizi della piattaforma, consultare le istruzioni per l'amministrazione di StorageGRID. Potrebbe essere necessario accedere al tenant da Tenant Manager per eseguire il debug di un errore del servizio della piattaforma.

.Fasi
. Per visualizzare l'allarme, selezionare *Nodes* *_Site_* *_Grid Node_* *Events*.
. Visualizza ultimo evento nella parte superiore della tabella.
+
I messaggi degli eventi sono elencati anche nella `/var/local/log/bycast-err.log`.

. Seguire le indicazioni fornite nel contenuto degli allarmi SMTT per correggere il problema.
. Fare clic su *Reset event count* (Ripristina conteggi eventi).
. Notificare al tenant gli oggetti i cui messaggi dei servizi della piattaforma non sono stati recapitati.
. Chiedere al tenant di attivare la replica o la notifica non riuscita aggiornando i metadati o i tag dell'oggetto.


.Informazioni correlate
link:../admin/index.html["Amministrare StorageGRID"]

link:../tenant/index.html["Utilizzare un account tenant"]

link:../monitor/logs-files-reference.html["Riferimenti ai file di log"]

link:../monitor/resetting-event-counts.html["Reimpostazione dei conteggi degli eventi"]
