---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: 'Prima di collegare StorageGRID come livello cloud FabricPool, si utilizza Gestione griglia StorageGRID per configurare un gruppo ad alta disponibilità (ha).' 
---
= Best practice per i gruppi ad alta disponibilità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di collegare StorageGRID come livello cloud FabricPool, utilizza Gestione griglia StorageGRID per configurare un gruppo ad alta disponibilità (ha).



== Che cos'è un gruppo ad alta disponibilità (ha)

Per garantire che il servizio bilanciamento del carico sia sempre disponibile per gestire i dati FabricPool, è possibile raggruppare le interfacce di rete di più nodi di amministrazione e gateway in una singola entità, nota come gruppo ad alta disponibilità (ha). Se il nodo attivo nel gruppo ha non riesce, un altro nodo del gruppo può continuare a gestire il carico di lavoro.

Ogni gruppo ha fornisce un accesso altamente disponibile ai servizi condivisi sui nodi associati. Ad esempio, un gruppo ha costituito da tutti i nodi Admin fornisce un accesso altamente disponibile ad alcuni servizi di gestione di Admin Node e al servizio Load Balancer. Un gruppo ha costituito solo da nodi gateway o da nodi Admin e nodi gateway fornisce un accesso altamente disponibile al servizio Load Balancer condiviso.

Quando si crea un gruppo ha, si selezionano le interfacce di rete appartenenti alla rete Grid (eth0) o alla rete client (eth2). Tutte le interfacce di un gruppo ha devono trovarsi all'interno della stessa subnet di rete.

Un gruppo ha mantiene uno o più indirizzi IP virtuali aggiunti all'interfaccia attiva del gruppo. Se l'interfaccia attiva non è più disponibile, gli indirizzi IP virtuali vengono spostati in un'altra interfaccia. Questo processo di failover richiede in genere solo pochi secondi ed è abbastanza rapido da consentire alle applicazioni client di avere un impatto minimo e può fare affidamento sui normali comportamenti di ripetizione per continuare a funzionare.

Se si configura un gruppo ha di nodi per il bilanciamento del carico, FabricPool si connette agli indirizzi IP virtuali di quel gruppo ha.



== Best practice per i gruppi ad alta disponibilità (ha)

Le Best practice per la creazione di un gruppo StorageGRID ha per FabricPool dipendono dal carico di lavoro, come segue:

* Se si prevede di utilizzare FabricPool con i dati del carico di lavoro primario, è necessario creare un gruppo ha che includa almeno due nodi di bilanciamento del carico per evitare l'interruzione del recupero dei dati.
* Se si prevede di utilizzare la policy di tiering del volume solo snapshot di FabricPool o Tier di performance locali non primari (ad esempio, ubicazioni per il disaster recovery o destinazioni NetApp SnapMirror®), è possibile configurare un gruppo ha con un solo nodo.


Queste istruzioni descrivono la configurazione di un gruppo ha per Active-Backup ha (un nodo è attivo e un nodo è il backup). Tuttavia, potrebbe essere preferibile utilizzare DNS Round Robin o Active-Active ha. Per ulteriori informazioni sui vantaggi di queste altre configurazioni ha, vedere link:../admin/configuration-options-for-ha-groups.html["Opzioni di configurazione per i gruppi ha"].
