---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: Utilizza questo semplice esempio di policy come punto di partenza per le tue regole e policy ILM. 
---
= Esempio di policy ILM per i dati FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza questo semplice esempio di policy come punto di partenza per le tue regole e policy ILM.

In questo esempio si presuppone che si stiano progettando le regole ILM e una policy ILM per un sistema StorageGRID con quattro nodi di storage in un singolo data center a Denver, Colorado. I dati FabricPool in questo esempio utilizzano un bucket denominato `fabricpool-bucket`.

[CAUTION]
====
Le seguenti regole e policy ILM sono solo esempi. Esistono diversi modi per configurare le regole ILM. Prima di attivare una nuova policy, simulare la policy proposta per confermare che funzionerà come previsto per proteggere il contenuto dalla perdita.

Per saperne di più: link:../ilm/index.html["Gestire gli oggetti con ILM"]

====
.Fasi
. Creare un pool di storage denominato *DEN*. Selezionare il sito di Denver.
. Creare un profilo di codifica Erasure denominato *2 più 1*. Selezionare lo schema di erasure coding 2+1 e il pool di storage *DEN*.
. Creare una regola ILM che si applica solo ai dati in `fabricpool-bucket`. Questa regola di esempio consente di creare copie codificate per la cancellazione.
+
[cols="1a,1a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome regola
 a| 
2 più 1 erasure coding per i dati FabricPool



 a| 
Nome bucket
 a| 
`fabricpool-bucket`

È anche possibile filtrare l'account tenant FabricPool.



 a| 
Filtraggio avanzato
 a| 
Dimensione oggetto (MB) maggiore di 0.2 MB.

*Nota:* FabricPool scrive solo oggetti da 4 MB, ma è necessario aggiungere un filtro dimensione oggetto perché questa regola utilizza la codifica di cancellazione.



 a| 
Tempo di riferimento
 a| 
Tempo di acquisizione



 a| 
Posizionamento
 a| 
Dal giorno 0 memorizzare per sempre



 a| 
Tipo
 a| 
Codifica di cancellazione



 a| 
Posizione
 a| 
DEN (2 più 1)



 a| 
Comportamento di acquisizione
 a| 
Bilanciato

|===
. Creare una regola ILM che creerà due copie replicate di qualsiasi oggetto non corrispondente alla prima regola. Non selezionare un filtro di base (account tenant o nome bucket) o filtri avanzati.
+
[cols="1a,1a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome regola
 a| 
Due copie replicate



 a| 
Nome bucket
 a| 
_nessuno_



 a| 
Filtraggio avanzato
 a| 
_nessuno_



 a| 
Tempo di riferimento
 a| 
Tempo di acquisizione



 a| 
Posizionamento
 a| 
Dal giorno 0 memorizzare per sempre



 a| 
Tipo
 a| 
Replicato



 a| 
Posizione
 a| 
DEN



 a| 
Copie
 a| 
2



 a| 
Comportamento di acquisizione
 a| 
Bilanciato

|===
. Creare una policy ILM proposta e selezionare le due regole. Poiché la regola di replica non utilizza alcun filtro, può essere l'ultima regola predefinita per il criterio.
. Acquisire oggetti di test nella griglia.
. Simulare il criterio con gli oggetti di test per verificare il comportamento.
. Attivare il criterio.


Quando questo criterio è attivato, StorageGRID inserisce i dati degli oggetti come segue:

* I dati a più livelli di FabricPool in `fabricpool-bucket` verrà eseguito un erasure coding utilizzando lo schema di erasure coding 2+1. Due frammenti di dati e un frammento di parità verranno posizionati su tre diversi nodi di storage.
* Tutti gli oggetti in tutti gli altri bucket verranno replicati. Verranno create due copie e collocate su due diversi nodi di storage.
* Le copie replicate e codificate in cancellazione verranno conservate in StorageGRID fino a quando non verranno eliminate dal client S3. StorageGRID ILM non eliminerà mai questi elementi.

